### ISSUE TITLE
Simming profiles together lower the DPS

### ISSUE THREAD

**Issue by navv1234** [simulationcraft/simc#2615]
Originally reported on Google Code with ID 2616

```
IF RUNNING FROM THE GUI, PLEASE ATTACH (or Cut-N-Paste contents) OF
simc_gui.simc FILE.  THIS WILL ENABLE TO US TO REPRODUCE THE PROBLEM.

What steps will reproduce the problem?
1. Sim 1 profile alone (for example, armory=us,illidan,karabor)
2. Sim multiple profiles at the same time
3. In the multiple profile simulation, the DPS will be lower

What is the expected output? What do you see instead?
All dps to be the same within margin of error

What version of the product are you using? On what operating system?
Windows 8.1 / most recent version

Please provide any additional information below.


```

Reported by `msubrian63` on 2015-08-06 21:31:34

**Comment by scamille** [comment]
The original idea, as far as I understand, was that the whole enemy health calculation should make the simulation model more realistic, because it can model the execute phase more realistically.

The problem here is that nobody sims a fully realistic raid setup, but either single characters or even the raid reports are likely distorted.

I would tend to vote for fixed_time as default setting as well, because the enemy health calculation has/had so many drawbacks and cause problems and discussions in the past.

**Comment by aggixx** [comment]
Might be worth adding some sort of improved fixed_time setting with regards to execute time? Its not very realistic to assume the last 20% of the bosses health lasts for 20% of the fight, but you also can't use the actor's DPS since then you have the warrior problem (boss explodes sub 20%). Almost seems like accelerating the health decline of the later parts of the fight by some arbitrary amount would be the most beneficial.

**Comment by mrdmnd** [comment]
Out of curiosity, at a high level, why can't we start supporting "whole raid" sims more commonly? Is it too computationally expensive? I feel like it's totally achievable without many code changes, we just need to add an option box that pre-populates the .simc with other players' stuff.

**Comment by navv1234** [comment]
Main reason why it is more or less a non-starter is that your simulation slows roughly by 25x if you simulate a "real" raid of 25 people.

**Comment by navv1234** [comment]
Oh, and re: @aggixx comment. Yes, it would be nice to add some sort of `fixed_time` option that knows how to correctly "speed" up the simulation past some health threshold. I think it would have to be a single-actor (or potentially, a homogeneous actor type) thing, otherwise it gets rather complicated to try to figure out when/how to exactly do it.

**Comment by scamille** [comment]
We could just add two options, a) threshold when to speed up (default 20% = 0.2) and b) speedup factor (ie. +10%, so 1.1).

Then for max_time=300 the execute phase would take max_time * threshold / speedup = 54.5s (instead of 60s with uniform time), and the pre-execute phase max_time - execute_time = 245.5s (instead of 240s).

In the end we'd need to calculate boss_health(time) function... Shouldn't be too hard

**Comment by navv1234** [comment]
We should probably actually add a player_t method that gives a "default threshold" for a given actor, so we would have a static value for it. Execute thresholds vary by class/spec after all. The speedup factor is the more tricky part here.

**Comment by Collisionc** [comment]
@mrdmnd As reia mentioned, it's a speed thing. Running stat weights for your character would take an hour on a relatively powerful i7-4790k if you did it with 20 actors. 

You can already do raid profiles, it's just a matter of if you're willing to wait that much time to test every small change that you make.

**Comment by scamille** [comment]
Hum I just had the idea that we could use SimC to collect Boss HP timeline data on a raid sim, save that to some output file, and then that can be used as input for a single-actor simulation.

Data could also be aggregated into buckets of iteration-length sets.

**Comment by scamille** [comment]
single_actor_batch=1 now offers a tested alternative way to simulate N actors sequentially each by itself, instead of performing in parallel with the default setting.
