### ISSUE TITLE
Cancelling Soul Capacitor buff (Spirit Shift)

### ISSUE THREAD

**Issue by RavenTwiki** [simulationcraft/simc#2621]
When the Maalus buff is active and Spirit Shift procs, it is sometimes a dps gain to cancel the Spirit Shift buff before Maalus expires, the breakpoint is when Spirit Shift will expire roughly 4.6seconds after Maalus expires. I added this line and expected a simmed dps increase:

actions+=/cancel_buff,name=spirit_shift,if=buff.maalus.remains<0.5&buff.spirit_shift.remains<4.1

The difference in dps was so small that I'm not sure if the explosion from cancelling Spirit Shift is happening.

**Comment by navv1234** [comment]
Your action cancels the buff, even if maalus is not up, since when the buff is not up, remains returns 0. Using something more realistic like `actions+=/cancel_buff,name=spirit_shift,if=buff.maalus.remains>0&buff.maalus.remains<1.5&buff.spirit_shift.remains<4.1` results in the following snippet in the debug log:
```
134.889 Shaman_Enhancement_T18M cancels buff spirit_shift
134.889 Shaman_Enhancement_T18M spirit_eruption hits Fluffy_Pillow for 805509 shadow damage (hit)
134.889 Shaman_Enhancement_T18M maalus stores 805509.26 damage from spirit_eruption on Fluffy_Pillow, new stored amount = 1222283.22
<snip some more lines>
136.057 Shaman_Enhancement_T18M performs maalus (32000)
136.057 Shaman_Enhancement_T18M amount for maalus: dd=352338 b_dd=1409353 mult=0.25
136.057 Shaman_Enhancement_T18M maalus hits Fluffy_Pillow for 352338 arcane damage (hit)
```

I'd suggest adjusting the action priority list command to actually ensure that the Maalus buff is always up, before cancelling the Spirit Shift buff, and seeing what the results look like then.

**Comment by RavenTwiki** [comment]
Apologies I had pasted an older line that resulted in a dps loss of about 1 to 1.5k. The new line I actually used is:
actions+=/cancel_buff,name=spirit_shift,if=buff.maalus.remains<0.5&buff.maalus.up&buff.spirit_shift.remains<4.1

**Comment by navv1234** [comment]
Sure, but the buff cancellation while Maalus is up correctly explodes, and correctly accumulates to the Maalus explosion. So, the model is functioning properly.

**Comment by scamille** [comment]
Closing this, since SimC apparently models the buff explosion correctly, 

If you have any enhancements for default action priority lists, please open a new ticket with the specific changes.
