### ISSUE TITLE
(rounding?) issue on either GCD or tick_time on Mind Flay (or more?)

### ISSUE THREAD

**Issue by kaesebrezen** [simulationcraft/simc#2623]
Based on a discussion on H2P here: http://howtopriest.com/viewtopic.php?f=75&t=7435&start=40#p67441

Description: Mind Flay's tick_time should always be 0.5 * GCD (this allows interrupts after the 2nd tick)

Problem: Simcraft can have MFs tick_time at less than 0.5 * GCD depending on haste.

Profile to use is linked here: http://howtopriest.com/viewtopic.php?f=75&t=7435&start=50#p67492

SimCraft values for gcd and tick_time() of mind flay with haste 100 and 150:

gear_haste_rating=100 : gcd  == 1.412 and tick_time == 0.706 (== 0.5 * GCD)
gear_haste_rating=150 : gcd  == 1.403 and tick_time == 0.701 (< 0.5 * GCD)

At 150 haste_rating either the GCD or the tick_time is wrong - this is a problem as with tick_time < 0.5 * GCD Mind Flay is no longer interruptable after the 2nd tick - and as seen in the linked discussion will result in a pretty odd dps curve for haste.

**Comment by scamille** [comment]
Thanks for opening the ticket. I was already trying to add some debug to the interrupt process to try figure out what the problem was, but you directly pointed it out:
At the time of the second tick, GCD is not yet ready, thus SimC does not allow interrupting Mind Flay.

Though I wouldn't conclude directly that tick_time and its special rounding is the cause of the problem here. After all it has received a lot of effort in the past, since it is/was responsible for the correct dot speed-up, and previously number of hasted ticks ( It still is, but now you have partial ticks to compensate). It very probably does what it should do, and we model mind flay tick times correctly.

I think the situation with tick_time rounding to slightly less than 0.5 * gcd is just a very unlucky coincidence here, and the root problem is that SimC only allows interrupting directly at the time of the tick, and not as in your 150 haste example 1ms later than the tick, at 1.403 instead of 1.402.

Any ideas how to resolve this @navv1234 ?

**Comment by navv1234** [comment]
Not sure what the problem with the tick time is, it seems perfectly OK with me. As serge said, the problem is that we only allow channel interruptions at tick intervals. Changing that requires code changes. One option would be to hack in an event that fires when gcd is over if you are channelling, that lets you do the cancellation check. The other, more proper solution is to redesign the whole system, meaning that we would support proper interrupts, whether it be casting spells or channeling them. This one is more extensive, and more costly processing-wise.

**Comment by kaesebrezen** [comment]
Main train of thought was more like:

MF ticks always happen at 0.5 GCD or 1 GCD -> MF tick doesn't happen at 0.5 // 1 GCD -> something is wrong with either GCD or tickspeed -> if GCD/ticks happen at same time, interrupts will work just fine.

But now allowing interrupts to happen outside of ticks seems like the proper solution, instead of a changing a 1/100 ms difference between gcd/ticks.

**Comment by natehieter** [comment]
Properly supporting asynchronous triggers is a problem similar to
expression caching in that we need watch points but do not want polling.

On Sat, Sep 5, 2015 at 5:25 PM, navv1234 <notifications@github.com> wrote:

> Not sure what the problem with the tick time is, it seems perfectly OK
> with me. As serge said, the problem is that we only allow channel
> interruptions at tick intervals. Changing that requires code changes. One
> option would be to hack in an event that fires when gcd is over if you are
> channelling, that lets you do the cancellation check. The other, more
> proper solution is to redesign the whole system, meaning that we would
> support proper interrupts, whether it be casting spells or channeling them.
> This one is more extensive, and more costly processing-wise.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simulationcraft/simc/issues/2623#issuecomment-137995312>
> .
>



-- 
When a ball dreams, it dreams it is a frisbee.......

**Comment by scamille** [comment]
In a completely redesigned system, how would you let the user specify the interrupt? Just add special interrupt actions, or a special syntax for the interrupt option?
eg. actions+=/mind_flay,interrupt=1,interrupt_at=1.0*gcd

**Comment by Twintop** [comment]
Either that or maybe:

actions+=/mind_flay,interrupt=1,interrupt_after_tick=2

**Comment by navv1234** [comment]
Sure, but if you go that route, the definition of a "watch point" is much more complicated for something like this, than it is to cacheable expression state. As an example, off-gcd actions do have support for something like this, and they poll.

**Comment by natehieter** [comment]
It is similar to the "marking as stale" portion of cached expressions.....
and similar to "trigger ready" I guess.  It gets back to our perennial
discussion on state changes that generate callbacks.  You don't completely
get away from polling, but theoretically it only happens at "interesting"
points.

On Sun, Sep 6, 2015 at 6:01 AM, navv1234 <notifications@github.com> wrote:

> Sure, but if you go that route, the definition of a "watch point" is much
> more complicated for something like this, than it is to cacheable
> expression state. As an example, off-gcd actions do have support for
> something like this, and they poll.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simulationcraft/simc/issues/2623#issuecomment-138061878>
> .
>



-- 
When a ball dreams, it dreams it is a frisbee.......

**Comment by scamille** [comment]
A quick fix/hack would be to manually override tick_time of mind_flay_t.

@navv1234 the question is how to define those "magic" points in time. for interrupt=1 option, one point in time is the gcd_ready, which would specifically solve the mind_flay problem.  
For all the other points in time, that would be every time a higher_priority_action becomes available,  which unless we get complete callback for actions getting ready means polling.
Handling interrupt_if expressions are basically the same for expression, coupled with the higher_priority check as well.
But you already know that.

**Comment by Collisionc** [comment]
I believe this has been fixed for Legion?

**Comment by scamille** [comment]
Not that I am aware of. But the problem will only occur again with high haste levels.

**Comment by navv1234** [comment]
@Twintop claimed some moons ago in IRC that it's actually fixed now somehow? Not sure if that's because of the haste or what, though.
