### ISSUE TITLE
Low DPS between 4 and 6 Enemies

### ISSUE THREAD

**Issue by fateswarm** [simulationcraft/simc#2637]
Take a look at those results:

http://www.mmo-champion.com/threads/1874998-Most-Frost-Mages-taking-Thermal-Void-when-SimCraft-shows-Prismatic-Crystal-higher?p=36537788&viewfull=1#post36537788

**Comment by scamille** [comment]
@simulationcraft/mage

**Comment by Frostedmages** [comment]
I responded on MMOc, but I'll copy/paste it here.

4 targets is when the AoE sub-APL is called over the ST sub-APL, and there has been very little work done on the AoE sub-APL. There is certainly room for significant room for improving the AoE sub-APL, but nobody really is interested in working on it. If you'd like to submit an improved one you can do so here (or on MMOc/AT) and I'll update the module/default profiles.

**Comment by kenthklui** [comment]
Frost AOE action list target number threshold were tuned based on Frost Bomb which was the top performing talent for most of WoD (and still is, for mass AOE scenarios), instead of Unstable Magic which has only become popular since 6.2. You won't find optimal cleave/AOE results for other talent combinations without doing some custom tweaking.
