### ISSUE TITLE
Opening Simulationcraft redirects to a website?

### ISSUE THREAD

**Issue by atom1cs** [simulationcraft/simc#2640]
Hello,

When I open SimulationCraft, it tries to open a tab in my browser, and it is trying to open the following website:

hxxps://bs.serving-sys.com/Serving/ActivityServer.bs?cn=as&ifrm=1&ActivityID=684285&acp=$$region=us$$&appuid=undefined&blzenv=web&rnd=0.03969869785942137

On the page it says:  "//Do nothing"

View page source has the same thing:  "//Do nothing"

Why does this application open this webpage?  Has the 64 bit installer been modified?
Its never done this before, so i am a bit concerned.  Googling for the domain doesn't necessarily garner confident results.

Please advise.

Thank you.
-Atom

**Comment by navv1234** [comment]
It's an issue in how the GUI treats external url clicks.

At some point in time, the battle.net (at least the US one) front page that the GUI loads in the import tab started serving content from that domain. The content somehow generates a click event in the WebEngine component of Qt, causing the Simulationcraft GUI to think the user clicked on that specific link on the page. Seeing as the domain is not something Simulationcraft GUI wants to display inside its own window, it delegates the loading to desktop services (i.e., your browser).

I do not know about the legitimacy of the actual request, but presumably it is OK since it comes from the advertisement services used on (us.)battle.net. The specific issue has been fixed in the codebase now, and the WebEngine no longer loads "user events" that it receives from sub frames on rendered web pages.

In the meantime, you can use the 622-01 nightly release, where the url is not delegated to desktop services. Releases can be found at http://downloads.simulationcraft.org/?C=M;O=D

**Comment by atom1cs** [comment]
Navv,

Thank you very much for the explanation.  I appreciate you looking into
this, and taking the time to describe the issue so succinctly.  Thanks for
the quick reply also!

Best Regards,
Atom

**Comment by scamille** [comment]
622-01 release is out there, closing this.

**Comment by atom1cs** [comment]
Thank you.
