### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by teyasio** [simulationcraft/simc#2652]
Would like to be able to change gear and resim without having to use a website to import from.  Easiest way I been doing this is to change gear in WoW, log out back in and import.  But this gets annoying especially when you have to sim a lot of gear.

**Comment by Frostedmages** [comment]
You can edit any imported profile by just changing the gear strings that follow the Action Priority List.

**Comment by teyasio** [comment]
Which makes it extremely difficult and tedious. I don't understand why the UI cant support this.

**Comment by Frostedmages** [comment]
I fail to see how editing a simple text trinket is difficult, or tedious?

**Comment by teyasio** [comment]
There's lot of different item levels, then you have upgrade levels, normal, heroic, mythic, etc.  Vs just clicking on a gear slot swapping it out.  The tool is great for sims. But be 100x better if it had a way to easily swap gear without having to import from another website.

**Comment by navv1234** [comment]
Have you tried http://www.curse.com/addons/wow/simulationcraft ?

**Comment by teyasio** [comment]
Haven't given that a try. I'll look into it.

**Comment by scamille** [comment]
This has been a long standing issue. To give you a short answer:

We do not have any plans to implement a graphical character planer into SimC at this time, because we simply do not have the man-power not only to develop, but also maintain it. Our focus lies on the core job of SimC, simulating and analysing WoW combat.

But we always welcomed third party tools, and have developed parsers for their apis (Rawr, wowhead, battle.net, etc. ), or offer our own import api which is eg. used by Ask Mr.Robot. If there are any other worthwhile system you like supported, or some enhancements which need to be done on our site, just contact us.
