### ISSUE TITLE
[Rogue] APL/sim cheat - Hemorrhage

### ISSUE THREAD

**Issue by Koxomathical** [simulationcraft/simc#2659]
Current version (simc-623-01-win64.7z	27-Nov-2015 16:53	33M) and your featured version on the website calculates with Hemorrhage in APL for Subtlety. Basically it is casted 0 times, but appearently this 0 cast results in a 0.2%ish uptime that is procced by Sinister Calling 0.2 times during a 240sec fight with 20% time range resulting in a 3.0 DPS gain which is false as using hemorrhage should never ever net a dps increase on single target except some extreme situations (not as extreme tho as a backstab/ambush multistriking 12 times after hemo is cast in less than 0.2sec).

**Comment by Aethys256** [comment]
It is done if you're far to have a Rupture and then losing SV, and in this case it's a dps gain.
We can see it ingame when we do switch target but it is VERY rare that this situation happen in purely ST except if we have a ton of luck on ms proc making the rupture going off and not having enough CP to put another one, then it's worth to hemo (if you have the glyph, of course).

It might be seen as 0 cast because of rounding.

**Comment by navv1234** [comment]
The 0 cast is due to rounding, yes. Or to put it in another way, hemorrhage is not executed every iteration due to the strict conditions on the execution.
