### ISSUE TITLE
75% Player skill simulation has more DPS than 100% Player skill on Ret Pala.

### ISSUE THREAD

**Issue by MoreliaBredlii** [simulationcraft/simc#2695]
Today when simulating some guild members/friends I noticed that 75% was showing higher DPS than 100% for Ret Pala.
[75 pala.txt](https://github.com/simulationcraft/simc/files/164365/75.pala.txt)
[100 pala.txt](https://github.com/simulationcraft/simc/files/164366/100.pala.txt)

Is this a bug or not? Could someone explain how this works and why it's showing lower DPS on higher skill?

**Comment by mrdmnd** [comment]
I mean, @mserrano will know more. This certainly looks like something is broken to me.

The 75 profile looks like it's processing 436 RPS whereas the 100 profile is processing only 367. It doesn't look like the 100 profile has 6.8% uptime on avenging wrath, whereas the 75 profile has 41% uptime. 

Thoughts, @mserrano ?

**Comment by Collisionc** [comment]
Nothing wrong here, it's just an odd talent setup that the action list doesn't properly deal with. At 100% skill, the action list never fails to follow instructions.

In the characters talent setup (Holy Prism, Final Verdict) there is only 1 line that can trigger AW in a normal simulation:

avenging_wrath,if=!talent.seraphim.enabled&time<20&set_bonus.tier18_4pc=1

That's pretty specific. It means that AW is only cast once per fight, and only in the very last 20 seconds which will probably not line up with anything. There are also a lot of lines in the action list that are looking to see if avenging wrath is currently up, so they will be used less as well. 

Lowering the skill "fixes" this problem because it has false positives (skipping an action when it should have been used) and false negatives. False negatives effectively ignore the conditions when triggered, which means that in edge cases such as this, where the action list was never made to take a certain talent combination into account, it can lead to higher dps by actually using the ability.
