### ISSUE TITLE
Character portrait in html report references wrong URL

### ISSUE THREAD

**Issue by henrikse** [simulationcraft/simc#2697]
The character portrait/thumbnail in html reports references the following url: 
https://us.api.battle.net/wow/character/realm/character/advanced

Clicking the image or following the link fails to load the (intended?) armory page: 
http://us.battle.net/wow/en/character/realm/character/advanced 

Noticed in 623-02

**Comment by mrdmnd** [comment]
For whomever comes after me on this issue, I think the relevant file is here: engine/interfaces/sc_bcp_api.cpp

Don't have time to handle this right now, but it might save you some seconds grepping.

**Comment by scamille** [comment]
To put this in other words: The first link represents the origin-url of the imported character, which uses by default the new battle.net API. That link itself is absolutely correct for what it represents, the origin of the data used for importing the character.

The problem here is that the html report just plainly uses this origin link for thumbnail picture link, when it might be better to let it point to the armory. In the past, when using the old armory-html parsing, those 2 links were identical and there was no problem.

So this would need adding some concept of player -> armory_url or player -> displayable_origin_url or something, and using that in the html report as the thumbnail link.
Or just removing the link behind the thumbnail ;)

**Comment by Collisionc** [comment]
I'm all about removing the link.
