### ISSUE TITLE
Prot Paladin 2pc not supported?

### ISSUE THREAD

**Issue by durandal42** [simulationcraft/simc#2699]
In a report on a paladin wearing three pieces of the "Ceaseless Vigil" set, the only healing sources listed are:
- holy_shield_absorb
- Arcing Light (lights_hammer_heal_tick)
- Sacred Shield (_tick)
- Seal of Insight (_proc)
- Shining Protector

I expected to see Avenger's Reprieve as well, but it's not there.

**Comment by IMM3612** [comment]
I am going to add to this.

Does Healing&Absorb tab only show class based spells then? It wasn't picking up warrior tier13_2pc and now I am testing 715 Heirloom Tank Trinket [Purified Shard of the Third Moon
] and it doesn't appear either.
Speaking of the trinket, there doesn't seem to be a difference running it against a demon and a non-demon enemy, spell_id=201414 (bonus absorb against demons) is used both times while normal absorb is 202052 (can not be found via query).
To avoid this in future, how do you manually write absorb to a trinket via _use_?

**Comment by scamille** [comment]
Looking at the [paladin code](https://github.com/simulationcraft/simc/blob/master/engine/class_modules/sc_paladin.cpp) I cannot find any implementation of T18 set bonus except for Retribution.

Ever since @theckhd quit WoW, our emerging but promising tank support has unfortunately more or less stopped evolving.
I thus can't really promise fixing this issue. Instead, we'd need someone interested in continuing to develop the prot-paladin module, especially with the upcoming legion addon.

**Comment by Collisionc** [comment]
Closing as won't fix with legion coming up.
