### ISSUE TITLE
Error when attempting very short fights.

### ISSUE THREAD

**Issue by fateswarm** [simulationcraft/simc#2704]
I attempted a 40sec fight with 0% length variation and I got many lines of 

_Simulation has been forcefully cancelled at 80.00 because twice the expected combat length has been exceeded._

It was on an arcane mage patchwerk setup.

**Comment by Frostedmages** [comment]
Impossible to diagnose without you uploading what you input.

**Comment by natehieter** [comment]
The 0% length variation is misleading.  To manage "execute" abilities, there is an adaptive algorithm that attempts to predict boss health to produce the desired fight length.  However, since this is an adaptive algorithm with a random element we are morally required as software engineers to add safeguards to make sure we don't create SkyNet by accident.

Joking aside: The bottom line is that there is too much relative variation in damage output over such a short fight to attempt to reasonably predict boss health.  A string of crits in one iteration makes the code over-compensate... follow-up with some misses and all of sudden the fight is lasting way longer than the desired 40sec, leading to the termination with extreme prejudice.

If you want to simulate such a short fight, I highly recommend using the "fixed_time" option...... and possibly some of the options related to execute range.  There has been some movement in that area in my "absence" so others will have to chime in there.

**Comment by kenthklui** [comment]
Arcane Mage DPS variance means that this cannot be fixed. The only option is to used fixed_time.

Also keep in mind that a "40 second fight" does not correspond to "first 40 seconds of a fight". The actions taken by the sim will be different.
