### ISSUE TITLE
Import Failed - Unable to generate profile on every character I try

### ISSUE THREAD

**Issue by Lordmajeh** [simulationcraft/simc#2757]
As stated in the title. Also should note that I cannot navigate the webpage in the import section so I went on the battle.net website to copy the url's and that consistently came up with import failed

Edit: updated to the 703-01 beta build and it succesfully imported, still doesnt work on 623-02 build

**Comment by Collisionc** [comment]
There's way too many changes on battle.net's end to get 623-02 working. 

You can also press "Ctrl + I" to bring up a widget that'll allow you to import your character on 703-01. Blizzard changed their site so that now when you click on a link to an armory, it always opens a new tab, and our "browser" was not setup to handle web-tabs, so it just doesn't go anywhere. 

You can also right click the link and "follow url" to get there.
