### ISSUE TITLE
[Question] Mythic+ gear for T19M/T19H

### ISSUE THREAD

**Issue by skasch** [simulationcraft/simc#2761]
Regarding gear limitation for equipment:
- Can mythic+10 drops be used for T19H? (ilvl 865, Mythic+ dungeons opens with EN MM)
- Can mythic+10 drops and order hall boxes be used for T19M? (boxes: ilvl 880, one per week)

**Comment by aethys256** [comment]
I don't think it's a good idea, since those profiles are not absolute BiS list but rather a display of what you should expect around this iLvl, and it would increase the gap between "well maintained" profiles and those not updated often.
Anyway, you can make this kind of profile for a "BiS List guide" if you want to, but putting them as default profile is a bad idea in my opinion.

**Comment by skasch** [comment]
I agree; I just think it's worth precising it, whatever the decision is.

**Comment by Collisionc** [comment]
Yeah, let's not allow mythic+ gear.  We don't even have T19M/H profiles for every spec in the first place. :)
