### ISSUE TITLE
Outstanding Warlock Issues

### ISSUE THREAD

**Issue by nasirabtw** [simulationcraft/simc#2815]
Throwing these here because I have no clue how to fix them.

1) The talent Hand of Doom is causing Doom to incorrectly tick more frequently than manually casting the DoT. Test profile: http://pastebin.com/XLNW6RPP

2) Wilfreds sigil of superior summoning is only proccing 50% of the time for wild imps.

3) Seed of Corruption seems to apply corruption to secondary targets but not report the damage it deals. Sample profile + debug output:

http://pastebin.com/knLTvLCN
http://pastebin.com/7LXWRwTF

The debug shows corruption ticking on 2, but an html report shows no uptime/dps increase over 1 target.

3) Felguard only executes felstorm once per fight despite having actions+=/felguard:felstorm in the apl.

**Comment by navv1234** [comment]
Darkglare fixed in 7b01aae.

**Comment by navv1234** [comment]
Shadowflame fixed in 12456de.

**Comment by navv1234** [comment]
Lord of Flames stuff fixed in 6e144e8.

**Comment by Collisionc** [comment]
Anything else needed here ?

**Comment by Symer** [comment]
Seed of Corruption and Felstorm are still bugged.

**Comment by Symer** [comment]
Felstorm bug is probably energy related. If you tell the FG to stop using Legion Strike using 

pet=felguard
actions=/wait

inside the profile, then Felstorms appear. I don't have any older versions that used to work to compare at this point, but it is possible that the pet is now coded to use its Legion Strike at 60 energy and it will keep him effectively bellow the minimum energy requirement before the player action list can do anything. AI in the game itself does not work like this, but lets the FG stock 85 energy or something so that the other abilities remain at hand.

Modifying the action list from the main profile is not fully working. Any condition placed on legion_strike gets ignored and it will always act like

actions=/legion_strike,if=energy>85
.
actions=/legion_strike,if=target.time_to_die<20
etc.

were only

actions=/legion_strike

although in the report sheet you see the pet action list used there in the form that was writen.

**Comment by nasirabtw** [comment]
The Hand of Doom bug pertains to this specific part of hand_of_guldan_t in the impact (ln 3242 warlock):

http://pastebin.com/YcTNHMHg

With HoD talented Doom is applied to any target hit on impact.

When you refresh Doom via HoD the end time of the DoT is correct but the tick time is massively reduced compared to a manual cast of Doom.
