### ISSUE TITLE
Rake dmg for feral

### ISSUE THREAD

**Issue by zoopercat** [simulationcraft/simc#2836]
To test Rake damage, you have to get rid of all of the other dynamic procs that happen. Here is a report just using Rake in a SimC report: https://postimg.org/image/4h8y0e6rv/
Here is the profile if you want to simulate it yourself: http://pastebin.com/Kzmbj2fs
Rake damage for this should be: 0.912_21360(AP)_1.5938(Mast)_1.0764(Vers)_1.21(Tear the Flesh)=40,438

SimC ticks for 42,784
The base Rake damage is adding in some other multiplier somehow. It's too high in SimC.

**Comment by mrdmnd** [comment]
@aggixx - I don't know if you're still doing feral stuff, but this is probably worth looking into.

**Comment by Tomslack** [comment]
No bug present that i can see from ingame checks. 

log of rake only rotation on dummy (used a non raid dummy however since rake ignores armor this won't affect results)
https://www.warcraftlogs.com/reports/7M3hYPQwmKRkDrCj/

wclogs rake damage
https://gyazo.com/f6708b60b90fccc56ed71d259c9da66e
sim rake damage
https://gyazo.com/782d8575adcf7aeb0380afa1da75fd42

profile used
http://pastebin.com/5yJvwf7B

sim results in .txt format
[rake_only.txt](https://github.com/simulationcraft/simc/files/475695/rake_only.txt)

**Comment by zoopercat** [comment]
I have never replied to a github, so I hope this works. I AM SO SUPER SUPER
SUPER SUPER SUPER ZOOPER Sorry ;)

I didn't get the relics setup right with the wowhead export / simc
manipulating. A rake relic accounted for it. As for the other bugs, let me
see if I can find time to dig through it some more to point you in the
right direction. Some of the damage #'s looked wrong, but it's hard to
isolate it with so many possible things affecting everything (like uh...
RELICS, sorrry again).

First, I have a big week getting ready for raid launch, then I might have
some more time.

Again, SORRRRRRRRRRRRRY!

**Comment by mrdmnd** [comment]
Hey, no worries! Good to double check, as you said. Relics are hard; I wish they made handling/interacting with them easier.

Good luck!
