### ISSUE TITLE
Simcraft crashing everytime I try to simulate 

### ISSUE THREAD

**Issue by Lati29** [simulationcraft/simc#2844]
Hello,

SimulationCraft is crashing everytime I'm trying to simulate something. I'm using the version 7.03.02, on Windows 10. I've talked about it with friends, and they're not facing this problem. I Don't really know how to fix that. The error message says : "The program has stopped working", and the only solution is to close Simcraft.

Thanks for your future help

Lati

**Comment by scamille** [comment]
Please provide the simc_gui.simc file found in your SimC folder (see https://github.com/simulationcraft/simc/wiki/simc_gui.simc).

Without knowing what character you are simulating, we can't replicate the problem.

**Comment by Lati29** [comment]
http://www.k-upload.fr/afficher-fichier-2016-09-17-19d264f02simcgui.simc.html

This is the profile i tried to simulate.

**Comment by Virezz** [comment]
i have the same issue.
crashes as soon as i click simulate
http://paste.ee/p/UsGM0

windows 10 tried compatibility mode aswell for win7-8 still same issue

**Comment by Collisionc** [comment]
@Virezz yours is crashing because we do not support healers at the moment, I have no clue hwy @Lati29 is crashing though. His profile works fine when I try it on windows 10.

**Comment by Collisionc** [comment]
@Lati29 can you post your dxdiag ?

Instructions:
Click on, "Start Button".
Click on, "Run".
In the pop-up window enter DxDiag and hit ok.
The DirectX Diagnostic Tool pop-up window should appear.
Click on, "Save all information".
"Save As" window should be present.
Click on, "Save" (The file should be saved to your desktop as DxDiag.txt)
Exit the DirectX Diagnostic Tool.

Upload the dxdiag file for us to look at.

**Comment by scamille** [comment]
I cannot replicate @Lati29 profile crashing as well.

@Collisionc We should check all healer specs, to at least return a not-supported message without crashing.

**Comment by Lati29** [comment]
http://www.k-upload.fr/afficher-fichier-2016-09-18-1b2e72f8fdxdiaglati.txt.html

Here's m dxdiag. Also, it's crashing the same way when i try to simulate the sample profile provided, and when I try to switch in EU server to import my character.

**Comment by Collisionc** [comment]
Does it crash as soon as you start the simulation, or does it crash when the simulation is done/nearly done?

**Comment by Lati29** [comment]
It only crash when the simulation is done.

**Comment by Helios12787** [comment]
I'm having my simC crash a couple seconds into the simulation (progress bar hits about halfway), then it either just crashes or my computer blue screens. It happens when I try to sim my character and the sample profile.  My character is an Arms Warrior so I'm pretty sure its supported.

**Comment by Collisionc** [comment]
Can you upload your dxdiag as well @Helios12787 ?

**Comment by Helios12787** [comment]
[DxDiag.txt](https://github.com/simulationcraft/simc/files/479245/DxDiag.txt)

**Comment by Collisionc** [comment]
Can you also upload the simc_gui.txt file that is in the same folder as simulationcraft.exe? After it crashes, upload that file here.

**Comment by Helios12787** [comment]
@Collisionc http://www.filedropper.com/simcgui

**Comment by Collisionc** [comment]
Try this version:

http://downloads.simulationcraft.org/simc-703-03-win64-15c616f.7z

**Comment by Helios12787** [comment]
@Collisionc Nope. Blue screen again. Want me to post the simcgui again?

**Comment by Collisionc** [comment]
When you say blue screen, you mean that you have to restart the computer, yes ?

**Comment by Helios12787** [comment]
Yea computer locks up, blue screens, and restarts. Just tried it again with the sample profile (it has a tendency to just crash simcraft and not my PC) but it blue screened as well.

**Comment by Collisionc** [comment]
This is kind of a shot in the dark, but I think you have hardware issues.  Are you overclocking the CPU/memory at all? 

Also, install/run this:  http://www.resplendence.com/download/whocrashedSetup.exe

Click analyze in the program, then just copy paste everything below "Crash Dump Analysis" here.

**Comment by Helios12787** [comment]
I am overclocking my cpu/memory but have never had stability issues (have run stability tests for close to 24 hours no problems).  Here's the crash analysis though.

Crash dump directory: C:\Windows\Minidump

Crash dumps are enabled on your computer.

On Mon 9/19/2016 10:29:08 PM GMT your computer crashed
crash dump file: C:\Windows\Minidump\091916-23984-01.dmp
This was probably caused by the following module: ntoskrnl.exe (nt+0x14A0D0) 
Bugcheck code: 0xD1 (0x0, 0xFF, 0x0, 0x0)
Error: DRIVER_IRQL_NOT_LESS_OR_EQUAL
file path: C:\Windows\system32\ntoskrnl.exe
product: Microsoft® Windows® Operating System
company: Microsoft Corporation
description: NT Kernel & System
Bug check description: This indicates that a kernel-mode driver attempted to access pageable memory at a process IRQL that was too high.
This appears to be a typical software driver bug and is not likely to be caused by a hardware problem. 
The crash took place in the Windows kernel. Possibly this problem is caused by another driver that cannot be identified at this time. 

On Mon 9/19/2016 10:29:08 PM GMT your computer crashed
crash dump file: C:\Windows\memory.dmp
This was probably caused by the following module: ntkrnlmp.exe (nt!KeBugCheckEx+0x0) 
Bugcheck code: 0xD1 (0x0, 0xFF, 0x0, 0x0)
Error: DRIVER_IRQL_NOT_LESS_OR_EQUAL
Bug check description: This indicates that a kernel-mode driver attempted to access pageable memory at a process IRQL that was too high.
This appears to be a typical software driver bug and is not likely to be caused by a hardware problem. 
The crash took place in the Windows kernel. Possibly this problem is caused by another driver that cannot be identified at this time. 

On Mon 9/19/2016 10:22:25 PM GMT your computer crashed
crash dump file: C:\Windows\Minidump\091916-21484-01.dmp
This was probably caused by the following module: ntoskrnl.exe (nt+0x14A0D0) 
Bugcheck code: 0x101 (0x18, 0x0, 0xFFFFBC817A661180, 0x2)
Error: CLOCK_WATCHDOG_TIMEOUT
file path: C:\Windows\system32\ntoskrnl.exe
product: Microsoft® Windows® Operating System
company: Microsoft Corporation
description: NT Kernel & System
Bug check description: This indicates that an expected clock interrupt on a secondary processor, in a multi-processor system, was not received within the allocated interval. 
This appears to be a typical software driver bug and is not likely to be caused by a hardware problem. This problem might also be caused because of overheating (thermal issue). 
The crash took place in the Windows kernel. Possibly this problem is caused by another driver that cannot be identified at this time. 

On Mon 9/19/2016 4:32:36 AM GMT your computer crashed
crash dump file: C:\Windows\Minidump\091816-15703-01.dmp
This was probably caused by the following module: hal.dll (hal+0x3620F) 
Bugcheck code: 0x124 (0x0, 0xFFFFD48BC2F48028, 0xBE000000, 0x800400)
Error: WHEA_UNCORRECTABLE_ERROR
file path: C:\Windows\system32\hal.dll
product: Microsoft® Windows® Operating System
company: Microsoft Corporation
description: Hardware Abstraction Layer DLL
Bug check description: This bug check indicates that a fatal hardware error has occurred. This bug check uses the error data that is provided by the Windows Hardware Error Architecture (WHEA). 
This is likely to be caused by a hardware problem problem. This problem might also be caused because of overheating (thermal issue). 
The crash took place in a standard Microsoft module. Your system configuration may be incorrect. Possibly this problem is caused by another driver on your system that cannot be identified at this time.

**Comment by Collisionc** [comment]
Yeah those are all blue screens typically related to overclocking. Simulationcraft stresses memory/cpu more than some stress test programs.  Disable the overclocking, see if it works, if it still crashes then it's possible that one of your sticks of memory is defective.

**Comment by Ben-Russell** [comment]
Hey, I was trying to help a friend sim and his character causes the program to crash similar to the other posters in this issue.

http://pastebin.com/stMWkm3v

When I import my own character I am able to run the sim fine, but importing his character causes it to crash.

703-02-win64
win 8.1

**Comment by navv1234** [comment]
Koltira's Newfound Will is the culprit there. I'll fix it tomorrow.

EDIT: Implemented in b36e9626b46d8b3ac2ed5df7ad4881c7096ffb5c

**Comment by Widoww** [comment]
I am getting this error too. Everything works until I click "simulate" followed by the program crashing. Reinstall and restart pc multiple times do not change anything.

my simc_gui file: http://puu.sh/rl1Ci.simc

Edit moments later: After going through these posts I re-imported my character and the sim works now.
