### ISSUE TITLE
Affliction profile dumping Unstable Affliction, when talented Contagion

### ISSUE THREAD

**Issue by Auteyus** [simulationcraft/simc#2860]
This is wrong.  It should be going for maximum uptime, as to maintain that sweet sweet 15% buff.  It should be overlapping just enough to get the upgraded damage of stacked Unstable Afflictions.

**Comment by scamille** [comment]
If you can, please provide exact action priority list changes, with tests that it improves DPS.

That way even non-warlock devs can directly update the default action list for you. Otherwise you are relying on class developer to do the work, which might not happen just because of lack of time, etc.

I'm closing this now with 7.1 changes. If its still a issue, please open a new ticket.
