### ISSUE TITLE
[Rogue] [Outlaw] Rotation uses gouge when position set to :back

### ISSUE THREAD

**Issue by Servatose** [simulationcraft/simc#2874]
When running a simulation for Outlaw Rogue DPS and choosing patchwerk style DPS, the sample table uses gouge as a free combo point generator.  Now, there are a couple of issues with this.  In my first screen shot, if I'm understanding correctly, it assumes your position is behind the target.  Gouge can only be used while you're in front of the target.  Not that big a deal, but the major issue here is that if a target is immune to gouge, which any training dummy/raid boss is going to be, it won't generate a combo point.  Here are some screen shots to illustrate what I mean.  Currently gouge is being used to generate free combo points:

Position Back:
![image](https://cloud.githubusercontent.com/assets/22342994/18706283/4df72468-7fe9-11e6-83e6-6609263a8625.png)

Gouge being used as a combo point generator:
![image](https://cloud.githubusercontent.com/assets/22342994/18706302/601b6730-7fe9-11e6-8013-254008e3821c.png)

**Comment by aethys256** [comment]
The thing is Gouge is only used with Dirty Tricks despite position and CC Immune.
I disabled it by default since the use of it is very trick (you have to go in front of the target basically).
Making positon swap into the APL isn't implemented (and I don't know if it will be someday), that's why this line is heavily documented in the APL.
Basically, you can quantify the effect of the Gouge with Dirty Tricks by enabling the right talent.
I do not recommend to use it by default for bosses nor use it if you don't feel confident in its usage.

**Comment by Servatose** [comment]
Ah, okay.  So the target "Fluffy_Pillow" isn't meant to simulate a raid boss?  Because gouge shouldn't award you a combo point if the target is immune, even with Dirty Tricks.  It seems like in that case I will also disable it.  Thanks for the reply!
