### ISSUE TITLE
Character imported with incorrect gear level

### ISSUE THREAD

**Issue by samohtnaj** [simulationcraft/simc#2983]
When I import my character to SimC the ilevel imported is not correct. It is quite a bit lower than reality. It seems like the scaled quest items are imported at their lowest possible ilevel.

The character is based in EU.

**Comment by Jackal42** [comment]
I am seeing this on a US-based druid too.  us,fizzcrank,Cerenor.  A specific example is that the headpiece imports as level 680, when the actual piece on the toon is 779.  Note that the import seems to work for my rogue.

**Comment by navv1234** [comment]
Quest items at the moment are very hard to import correctly from armory, because the armory does not give us the level you attained the item. The simulationcraft addon will correctly include that in the profile. I will take a look if there's some ugly workaround we could do for this, but I am somewhat doubtful.

EDIT: So, I just added a slight hack, where by drop-level based items (quest rewards basically) should start importing correctly with ilevel. This is a bit unknown territory for us though, so we'll have to see if this breaks something else in the whole armory importation.
