### ISSUE TITLE
Heavy discrepancy in Wdps scaling sim

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#2991]
http://imgur.com/a/GLkxu

I simmed twice with the same gear and setup, and I had greatly varying results for Wdps scaling. It just about always comes out around 0.95 (normalized) like the second picture, but when I saw 0.64 I knew something was up. Not a big deal to me personally as Wdps isn't something I can really customize for my character, but thought you guys might wanna know this happened. Seemed to be outside the margin of error for such a big discrepancy to occur.

10003 iterations for both.

**Comment by Collisionc** [comment]
Weapon damage has fairly high variance, and probably needs 25-50k iterations to get a solid value.  I'll take a look into it though.

**Comment by Collisionc** [comment]
Ok, should be much better after that change. Not sure why we had the delta set so low for it .

**Comment by scamille** [comment]
It should still roughly be inside the dps error boundaries, no matter how much it varies.
So eg. if you run the scale factors 100 times, 95 samples should have a maximum range of about 2*dps_error. (If I understood this stuff correctly, I'm no statistician.)

As far as I remember, there are a couple of hacks throughout the modules because setting the scaling delta for weapon dps happens later than some modules initialize stuff. Maybe some problem there.
