### ISSUE TITLE
Lack of XML generation

### ISSUE THREAD

**Issue by chrischenmingle** [simulationcraft/simc#3072]
For the last nightly or two that I've downloaded, I've been able to sim (and scale) but when trying to look at the xml to copy/paste into SWS, I get an error saying:

`Error opening . No file name specified`

I've tried renaming the tab, but that didn't work... can't find anyone else with the same problem either.

Not sure what you need as far as information, but running Windows 8.1 x64, using /simc and copy/pasting into the Simulate tab.  25k iterations, simming a rogue (all 3 specs) with scaling on all stats except WDPS/OWDPS/AP/SP. "SimcSetup-710-01-Win64.exe" 2016/10/30 15:08

**Comment by jeremynpross** [comment]
I have this same issue. I can't find any solution online. Can it be solved by rolling back the version of SimC? I hope someone gets assigned!

**Comment by FreeNickName** [comment]
SimcSetup-710-03-Win64 - similarly

**Comment by FreeNickName** [comment]
After studying the wiki, I found a way around this problem!
You must go to the Overrides tab and write something like `xml=C:\Users\xxx\Desktop\report.xml`
More in [https://github.com/simulationcraft/simc/wiki/Output#reports](url)
Just remember that your simulationcraft must have access to your path, for example, in my case `C:\report.xml` not work, probably due to lack of administrator rights

**Comment by navv1234** [comment]
As stated above, XML report now is gone from GUI, you can add it with the ```xml``` option in the overrides path.
