### ISSUE TITLE
[Druid] Balance artifact weapon showing ilvl 840

### ISSUE THREAD

**Issue by Aranui** [simulationcraft/simc#3079]
I noticed after patch 7.1 when I ran simulationcraft my dps dropped from about 318k to 280k. When I look at the results and click on gear, it shows my artifact weapon having an ilvl of 840. My artifact is in fact 885 and I think this is what caused the dps loss. 

My character is Arânui on Barthilas

**Comment by adam-kelsey** [comment]
I noticed this as well as a balance druid. As soon as I put in a karazhan relic the night it came out my sim dps went from 353k to 309k. I realized that my relic weapon was reporting at ilvl 844 instead of 890. Now that it says that all updates have been added I re-downloaded everything and set it up and ran it, and it still shows ilvl 844 weapon instead of 890.

**Comment by navv1234** [comment]
Would need a region/server/character to see what's wrong. We added kara items in 710, so it should all be ok.

**Comment by adam-kelsey** [comment]
North America, Sargeras, Ebrithill is the character.

http://us.battle.net/wow/en/character/sargeras/Ebrithill/simple

**Comment by navv1234** [comment]
Looks like some of the kara relics (possibly othe rstuff too) is not in client data.

**Comment by navv1234** [comment]
Should be fixed whenever the next nightly binaries for windows are built, or when we release 710-2.
