### ISSUE TITLE
[Trinkets] Devilsaur Shock Baton and Swarming Plaguehive damage values not matching ilvl version/in-game tooltips

### ISSUE THREAD

**Issue by Melvalint** [simulationcraft/simc#3123]
When simming an 845 ilvl version of the Devilsaur Shock Baton, the damage value on the tooltip is reporting the damage of an 835 ilvl version and being used in the sim.

Also, while simming an 865 Swarming Plaguehive the damage value is also off compared to the in-game tooltip.

**Comment by navv1234** [comment]
The tooltips in HTML reports (which is what I presume you are talking about here) are coming from Wowdb, we have no control over them other than giving them information on what the item is. You can check the value simulationcraft uses if you open the detailed breakdown of the ability in the HTML report. On the right side is a table called "direct damage". That table contains entries "base_dd_min" and "base_dd_max" for the minimum and maximum base direct damage of the proc. If those are also too low, we are going to need a profile to look into what the problem is exactly.

You can also verify from the "gear" breakdown in the HTML report to see what item level the item Simulationcraft thinks it is. Each item will contain an "ilevel" value in small text below the item name, which is what the simulator uses in its processing. Note that this may be different from the tooltip value if you hover over the item. Again, these tooltips come from Wowdb, and we have no control over them.
