### ISSUE TITLE
Checking Items In-Game

### ISSUE THREAD

**Issue by jmrathbun** [simulationcraft/simc#3174]
I have a feral druid around i850 and have been using your fascinating software to evaluate gear for a couple of weeks now. What I'm finding is that iLevel of an item is only weakly related to how it compares using your suggested stat weights, and it's also VERY cumbersome to use.

I'm posting here to get your feedback on my interpretation of your output, and to suggest the next step: automate the process of evaluating gear stats within the WoW interface (or in combination with something like ElvUI).

Yesterday I picked up a dandy necklace
![necklace](https://cloud.githubusercontent.com/assets/23525861/20393179/d2ac4f58-aca8-11e6-9e24-bf8971e7734b.jpg)
thirty iLevels higher than the one I had on. Comparing it with the older item for my cat, I used the following formula: VALUE = SUM(DIFFERENCE x WEIGHT). The result was astounding! The new item (Epic, Titanforged, i860) under-performed the old one (rare, heroic warforged, i830) by 34 points. Switching to Bear stats I got a far different result: the new item outperformed by 3019 points.

Does it appear to you that I understand how to use the software? And is there any hope of making the calculations less burdensome?

**Comment by jmrathbun** [comment]
Just FYI, this AM I ran the utility on my cat for the third time. The differences in weights were trivial, suggesting your software is operating consistently. In case it helps, here's what I got for Cat form:
Agi = 1.00
Vers = 0.66 (0.64)
Mas = 0.64 (0.67)
Crit = 0.61 (0.61)
Has = 0.39 (0.43)
(n) = last time 
The differences between applications 1 and 2 were more substantial, probably because I changed how I was selecting gear based on the results from application 1. 

My Bear numbers are 
Arm = 37.58 (40.65)
Vers = 3.16 (3.23)
Has = 1.83 (1.59)
Crit = 1.51 (1.48)
Agi = 1.00
Sta = 0.17 (0.25)
Mas = 0.13 (0.10)

**Comment by jmrathbun** [comment]
Just out of curiosity, does anybody read this stuff?

**Comment by Collisionc** [comment]
Yes, we do. I can't speak for others who work on the project, but I've been super busy IRL and since WoW has turned into an insane grinding fest, it's hard to split up free time with simc and WoW. :\ 

It does appear that you know how to use our program, and the results you are seeing are what a lot of specs are currently seeing. Until recently I was using a 830 ring due to itemization + a socket. 

I don't know of a way to make the calculations easier though. There are addons that can help with comparing items, like: https://mods.curse.com/addons/wow/simbuilder
