### ISSUE TITLE
Ring of Collapsing Futures damage too high

### ISSUE THREAD

**Issue by forecore** [simulationcraft/simc#3198]
Running a simulation with a Ring of Collapsing Futures (875)  --  Collapse Damage is too high (minimum 133k in SimC as opposed to ~72k on life for my UH DK).
The base damage of the spell is static 40k on life servers but seems to scale with itemlvl in Simulationcraft.

**Comment by Collisionc** [comment]
Oh, the 40k never changes? Weird.

**Comment by Maive23** [comment]
I have solved this problem.  To fix its damage, type the following into the "Simulate" tab in SimC:

override.spell_data=effect.353718.average=0

This will override the scaling factor for the spell "Collapse" so that it always does its base damage (any damage multipliers, like Symbols of Death for Rogues, will still go into effect)
