### ISSUE TITLE
[Sub Rogue] Mantle of the Master Assassin procs too often

### ISSUE THREAD

**Issue by FrozenSoviet** [simulationcraft/simc#3318]
Simc version 715-01, build 97f964f.

Currently for subtlety rogue, Mantle of the Master Assassin procs every ~42 seconds, which far over inflates its value. This is impossible ingame. See
![image](https://cloud.githubusercontent.com/assets/24901756/21621972/66416222-d1c9-11e6-9071-1cf0d04bae5f.png) from http://simc.aethys.eu/rog_sub_t19m_1t_legendaries.html.
Not an issue with Sin or Exsang, possibly Outlaw, hard to tell due to true bearing.

**Comment by bitfluxhound** [comment]
after looking in more details, the uptimes are correct, but it seems that the issue is caused by what happens when you vanish : 
![image](https://cloud.githubusercontent.com/assets/6678789/21625342/3a82f15e-d1d9-11e6-877a-0e69bbd40913.png)

http://i.imgur.com/M3V9Q4E.png

**Comment by aethys256** [comment]
Aura is the aura you got when you're stealthed, the buff without the aura suffix is the 6s buff.
Stats are weird to "see" then since there is 2 type of buffs. (It's exactly like Master of Subtlety)

PS: The only thing I'm not sure is the behavior with subterfuge.

**Comment by Pachelbe1** [comment]
I'm still seeing unusually high numbers of Mantle of the Master Assassin procs. I think, in part, Subterfuge is causing it to re-proc because the code thinks the actor re-stealths after regular stealth ends and Subterfuge begins.

If that's not the case, then I'm not sure what the problem is, but it definitely is a problem. The sim has the buff gained between 8-12 times when a raid fight of similar length only gains the buff 3 times, maybe 5 if cheesing with Sprint is actually a dps gain.

**Comment by aethys256** [comment]
Any logs ? (SimC)

**Comment by Pachelbe1** [comment]
Here's a log: http://pastebin.com/9BiMWnQL

I'm not really code-savvy so I'm not sure how to diagnose anything. Let me know if you need anything else.

**Comment by bitfluxhound** [comment]
Number of times buff is gained or lost is not important, since uptime is correct. This is due to how it is coded.
