### ISSUE TITLE
[Balance Druid] Nature's Balance not working correctly

### ISSUE THREAD

**Issue by Gebuz** [simulationcraft/simc#3344]
#### Simulationcraft Version
simc-715-01-win64-2591f9e

Nature's Balance seems to be extending both dots way more than it is supposed to. A single cast of Moonfire and 3 casts of Sunfire is enough to keep 100% uptime on a 300s sim. I'm guessing it could be that the duration is not correctly being reduced by haste in the sim, but I'm not sure. Without NB, the number of dot casts looks correct, so must be something about NB.

Another small bug:
Lady and the Child seems to not increase Moonfire damage at all (should be 20% - I don't know if it is additive or multiplicative with the artifact trait however).

**Comment by Hyperion244** [comment]
I noticed this too, a few weeks ago I helped @Collisionc fix Nature's Balance so that it extended dots properly (see https://github.com/simulationcraft/simc/commit/134749fa09e034baa36056a11c7bfd73a9206d37 and https://github.com/simulationcraft/simc/commit/165b5e07f7f9895e0cabfda9525f98c195ee8d41).  My guess is that it is snapshotting haste before the sim is run, and doesn't update dynamically before each cast.

**Comment by Collisionc** [comment]
I'll check it out later today

**Comment by Collisionc** [comment]
21.447 Druid_Balance_T19M extends duration of sunfire on Fluffy_Pillow by 1.6 second(s).
21.447 Rescheduling event DoT End (194) from 28.86 to 30.46

22.489 Druid_Balance_T19M extends duration of moonfire on Fluffy_Pillow by 3.6 second(s).
22.489 Rescheduling event DoT End (221) from 43.56 to 47.13

Does that seem like reasonable duration extensions? The T19M druid has 23% haste, but it looks like it also has some haste procs as that number varies somewhat. 

The haste is being updated. 

The druid casts lunar strike every 4.4 seconds, and solar wrath every 3.2 seconds.

**Comment by Gebuz** [comment]
``22.489 Rescheduling event DoT End (221) from **43.56** to **47.13**``
Are those numbers the duration of the dot or the time in the sim where they should end? Duration caps at usual pandemic duration (1.3*duration).

I assume that 1.6 and 3.6 is during Lust and/or INC? I believe it works exactly like cast time reduction, so 3.6s duration would mean 6/3.6=66.7% haste at the time of the extension.

**Comment by Hyperion244** [comment]
> Are those numbers the duration of the dot or the time in the sim where they should end? Duration caps >at usual pandemic duration (1.3*duration).

Ya @Collision I was slightly off here https://github.com/simulationcraft/simc/commit/134749fa09e034baa36056a11c7bfd73a9206d37, the max durations should be 28.6 for moonfire and 23.4 for sunfire, instead of 29 and 24, respectively.

Additionally, I was wrong about the scaling of Nature's Balance, the actual formula is as Gebuz said maxExtension/(1+haste), so if you have 66.7% haste the formula for moonfire is is 6/(1+0.667)~=3.6. I apologize for screwing that up, I should have been more careful in my testing.

**Comment by Collisionc** [comment]
no worries, that's an easy fix

**Comment by Collisionc** [comment]
With around 19%~ haste at the time of extension, this is what happens: 

112.779 Druid_Balance_T19M loses casting
112.779 Druid_Balance_T19M extends duration of moonfire on Fluffy_Pillow by 5.0 second(s).
112.779 Adjusting reschedule of event DoT End (642) from 133.55 to 138.59 time=118.43

The druid still only casts each once to maintain 100% uptime though.  The druid is just casting solar wrath and lunar strike enough to maintain the dot on the target.

**Comment by Gebuz** [comment]
It does seem possible I suppose. I'm surprised that it is possible even with The Emerald Dreamcatcher that casts significantly less Solar Wraths/Lunar Strikes the ED APL might need a small adjustment so that it intentionally drops moonfire, I'll look into that. The number of casts * dot extension seems to match, even when disabling all temporary haste buffs.

**Comment by Collisionc** [comment]
Ok, I made a slight mistake with my haste calculations that I fixed here - https://github.com/simulationcraft/simc/commit/2724259b9e6129597af6aa180365166d754c5b5e

Basically it was doing this - 
2 - 0.8 = 1.2 = 20% haste

When it needed to be doing this -
1 / 0.8 - 1 = 25% haste

Bit of a difference, especially with higher haste values. >_>  That might be enough to force the moonkin to reapply dots.

**Comment by Jundarer** [comment]
I don't know what exactly went wrong but in a patchwerk fight there is still just one application of mf and sf over 5 mins even though that is impossible in game.
