### ISSUE TITLE
Prot Warrior: Devastator and vengeance talents

### ISSUE THREAD

**Issue by Ragatokk** [simulationcraft/simc#3368]
The devastator talent seems to just add its damage to auto_attack_mh

I got some weird results trying to sim with the vengeance talent, it resulted in haste simming negative on dtps: http://i.imgur.com/XKvMjxh.png

Also thunderclap should be added to the single target dps rotation when you have chosen devastator.

What I simmed:
http://pastebin.com/jMRK1un2

**Comment by Collisionc** [comment]
Yeah that was a 4 AM addition last night, I need to look over it and see what I need to fix.

**Comment by Collisionc** [comment]
So... this is kind of interesting. Adding haste is increasing your damage taken per second because abilities are being used slightly sooner than they were previously, shifting where damage is taken time-wise in such a way that it leads to spell reflection being used at a slightly different time. 

This slightly different timing ends up resulting in a lower uptime for spell reflection when it matters, as incoming_damage_2500ms doesn't check to see if it's magic or not. 

This means that the spell_nukes that your custom enemies are casting on a 24 second cooldown are not being reflected nearly as often, which increases damage taken significantly. 

If you change the cooldown on the spell nuke from your custom enemies to be a bit more random, aka 14/18/20 seconds for enemy 1/2/3 instead of having all 3 enemies cast every 24 seconds, haste becomes a DTPS reducing stat. 



How should devastator work?

**Comment by Ragatokk** [comment]
Devastator uses a devastate on every auto attack, so the damage should be shown as devastate not auto attack.

I am not sure but I think that the prioritization for a warrior with the talent would be something like this:

Spell reflect
Demo shout
Last stand
Shield wall
Battlecry
Shield block

Ignore pain if rage >=40 and cost is reduced by vengeance and (you do not have ignore pain buff on OR you have less then 10% remaining of the shield adding another would give you)
Revenge if rage >=70 and cost of ignore pain is not reduced by vengeance
Neltharions Fury if you do not have shield block buff and there is >=3 sec til you get a charge.
Shield Slam
Revenge if free.
Revenge if rage >=100
Thunderclap
Revenge if reduced cost by vengeance and rage >= 60
revenge if rage >= 70

**Comment by Collisionc** [comment]
does devastator proc deep wounds ?

**Comment by Collisionc** [comment]
Nm, I figured out that it does proc deep wounds. 

If you make a new action list with that I'll add it, but for now I am closing this issue. :)
