### ISSUE TITLE
[SV Hunter] Implement Ranger's Net

### ISSUE THREAD

**Issue by Meatwookie** [simulationcraft/simc#3370]
Ranger's Net is not implemented into SimC right now,
but its the Spell SV Hunters can use to trigger Sephuz on Raid-Bosses

**Comment by Collisionc** [comment]
Last I checked it was working on nightly builds. http://downloads.simulationcraft.org/?C=M;O=D - top downloads are most recent

**Comment by Meatwookie** [comment]
oh ye was jsut me using another 7.1.5 build

**Comment by Meatwookie** [comment]
it is in the build, however it's not using it at all

**Comment by Jayezi** [comment]
It's using the apl you proposed which does not include it. Do you have a suggestion for where it should be placed in the priority? actions+=/rangers_net,line_cd=30 will trigger the ring on cooldown, if you want to play with it or I can use whatever priority Effin used for it to make his sims, but I personally have no idea since I have hardly looked with anything SV this expansion.

**Comment by Meatwookie** [comment]
ye i fixed it now,
wasnt specced into ranger's net

im dumb
