### ISSUE TITLE
Rogue Outlaw stats weights

### ISSUE THREAD

**Issue by NicolasMuzette** [simulationcraft/simc#3391]
#### Simulationcraft Version  =>715-01

Hi everyone. First time i use Girhub ^^'

I've used the last version of simcraft to calculate my stats weights as rogue outlaw with my character, using "Scaling" ... and it gives me :
                        Agi	          Vers	 Haste	Crit	     Mastery	
Scale Factors	17.16	11.56	10.89	10.48	8.33	

I don't get it. Why does Vers>Crit ? because for dps, 1%crit ~= 1%versa, and versa need more points to get 1% than crit. Shouldn't crit be better than vers ?

Thanks btw for this amazing app :)

**Comment by ZeratuleTheExalted** [comment]
Though I'd have to simulate your character in comparison, the reason any stat will become higher than others in scaling factor is if you have too much/too little of a particular stat. Technically speaking, you could have a character with 10,000 crit, and only 3,000 of each of your other stats. If you were to do this, the value of critical strike would deprecate dramatically in comparison to the other stats. Although you have a stat 'priority', you still need a pretty even balance for certain specs, Outlaw being one of those especially. This is apparent by your valuation of haste being above crit, meaning you have little to no haste most likely. Due to this, the program is noticing that it would give moderately more DPS to have a little extra haste, but if you stack too much it'll lower in the hierarchy.

**Comment by NicolasMuzette** [comment]
Ok, i get it for the haste. I think too that i may need some more energy regen, but my question is realy about versa and crit.

Even if i got a good crit score, as long as i don't reach any cap with my crit, i don't get how they can be a case where Versa>Crit. It still don't make any sense to me, correct me if i'm wrong (and i'm prety sure i am ^^):

1%versa = 1% dps = 475pts
1% crit ~= 1% dps = 400pts if i don't reach any cap. The only one i can think about is the 100%crit cap on pistol shot with my 40%crit, +24%crit on Gunslinger, +25%crit with RotB(Shark Infested Waters) =>89%crit

I also have a trinket that may proc +12,35%crit, so that's 1.35%crit on pure loss on each pistol shot in rare cases where i have my crit trinket proc +  RotB(Shark Infested Waters)

Is that the reason why my crit's scale factor drops ?

My character is Shenzee on Khaz-modan (eu)

**Comment by aethys256** [comment]
It's because you can see each stats a a dmg modifier. While it's not directly something that increases your dmg by x%, you can translate it by a dps gain. This is a normal behavior. SimC, according to the given context (and simulation model), will tell you that you should go for this or for this.
I recommend you to read this [wiki page](https://github.com/simulationcraft/simc/wiki/StatsScaling).
Altough, Outlaw need some sort of APL update according to latest changes, if you have any idea to improve it, feel free to contribute.
