### ISSUE TITLE
[Balance] Force of Nature (Talent) not updated for 7.1.5 hidden changes

### ISSUE THREAD

**Issue by Slippykins** [simulationcraft/simc#3408]
SimCraft version 715-01

Force of Nature now inherits the player's Haste, Crit and Versatility ratings, as well as snapshotting any buffs currently on the player. This was an undocumented change in 7.1.5.

**Comment by Collisionc** [comment]
joy be to undocumented changes

**Comment by Collisionc** [comment]
Doesn't even look like it's even implemented in simc, it'll have to wait until 715-02

**Comment by Collisionc** [comment]
Do they cast wrath still? Autoattack?

**Comment by Slippykins** [comment]
Yep they function exactly the same as before, with the annoying movement and bad AI. Only change is the stat scaling. From what I've seen ingame it captures Haste, Crit and Versatility ratings, not Mastery as that wouldn't make sense. It also updates those stats with any buffs on the character but has about a 2 second update refresh on stat changes. All stats when the trees are summoned are immediately applied.

**Comment by Collisionc** [comment]
Can you find the spell id for the spell they cast? It seems like it changed sometime in the last year.

**Comment by Slippykins** [comment]
So I've been informed that they don't cast Wrath anymore, and they additionally scale with Int.

So the scaling stats are Intellect, Crit, Haste and Vers. Only auto-attacks.

**Comment by Gebuz** [comment]
From beta blue post:
"Force of Nature now has attack power equal to 300% of your spellpower, and it also has your crit, haste, and versatility."

source: http://blue.mmo-champion.com/topic/409203-theorycrafting-questions/

I want to say that their default swing timer is 1.5 seconds, but I'm not sure, so probably better to test to make sure this is correct.

I believe the stealth buff in 7.1.5 was ~30-40%, I will see if I can get the exact number.

**Comment by Gebuz** [comment]
On snapshotting: It seems that they update every few seconds, but it does not seem very consistent. Unless someone knows exactly how this works  I think modeling them assuming that they just snapshot on cast or on cast and every X seconds for the duration seems reasonable.

**Comment by Collisionc** [comment]
https://github.com/simulationcraft/simc/commit/0c08f2d220c9fd0cb64d989d6b4143f3e1376e4b

some work done there, i'll get it finished up today hopefully

**Comment by Collisionc** [comment]
Ok, you'll need to check the damage of the pets to see if it matches in-game.  It should be fairly close... but there could be something I'm missing.

**Comment by Gebuz** [comment]
ran a few sims today, it needs a ~14.5% buff to match up with in game numbers just looking at the dmg per melee swing (looking at only normal hits, not including crits to reduce variance). I tested it with different gear to make sure the difference was consistent (removed 2 int trinkets, then 2 trinkets and neck + helm):
in game dmg per swing - sim dmg per swing - percent buff to make up the difference
65.694 ------ 57.378 ------  14.50%
59.734 ------ 52.173 ------ 14.50%
54.093 ------ 47.246 ------ 14.50%
I forgot to change amount of vers, I had 4.75% for all tests. Just in case that becomes relevant.

Number of hits seems on the low side aswell. I unequipped all haste procs I had, and disabled bloodlust/INC/CA so that I didn't have any haste buffs.
haste - sim # of hits - in game # of hits
0% ---------- 4 ------ 6
23.24% ------ 6 ------ 7
43.21% ------ 7 ------ 8
I did some in game testing, and I think I found the reason why this might be happening (or atleast part of it). Looking at this log where I use 0 haste: https://www.warcraftlogs.com/reports/qCyVkp2vDFz8WBJh/#boss=0&difficulty=0&view=events&type=damage-done&source=2&ability=-205636&start=244294&end=257320
The time between attacks is 2 seconds, but their first attack happens the same milisecond as they are summoned, and they do a final hit just before they disappear, resulting in 6 hits where we might expect 5. This doesn't completely explain the sim only having 4 hits though. I don't know how to check for damage events in simc, so I'm having some issues troubleshooting it.

I hope this helps :)

**Comment by Collisionc** [comment]
The only place I can think of where 14.5% damage would come from is the 15% from your artifact. Can you test that by trying it with a different weapon ?

**Comment by Gebuz** [comment]
Yep, that'd be it, numbers match up when testing without artifact.

**Comment by Collisionc** [comment]
alrighty, it should 99.99% match now, but please double check the latest download here - http://downloads.simulationcraft.org/?C=M;O=D - to make sure.

**Comment by Gebuz** [comment]
yep, spot on now, thanks :)
