### ISSUE TITLE
Fire Mage, Legendary, Koralon

### ISSUE THREAD

**Issue by Medi94** [simulationcraft/simc#3413]
The Legendary is propably wrong calculated.

In the source code I found the following instruction for the spell "scorch".
The percantage on live Servers is 30% and has a 100% critical hit Chance. I didn't found the 100% critical hit Chance or scorch. I haven't checked the damage Multiplier, but it should be correct, because it is still on +350% dmg.
Also if you start a new Simulation for a fire mage, the condition is still on 25%. It should be incresed up to 30% (which I changed manually for my Simulations)

    if ( ( koralons_burning_touch_multiplier > 0.0 ) && ( target -> health_percentage() <= 35 ) )

If you have any questions for this legendary, I give my best to help.

#### Simulationcraft Version
710-03

**Comment by vituscze** [comment]
Damage multiplier: https://github.com/simulationcraft/simc/blob/legion-dev/engine/class_modules/sc_mage.cpp#L6017

100% crit chance: https://github.com/simulationcraft/simc/blob/legion-dev/engine/class_modules/sc_mage.cpp#L6029

As for APL checking for <30%, this has been fixed in newer versions of SimC.

**Comment by Medi94** [comment]
Great, thank you
