### ISSUE TITLE
[Retribution Paladin] CoF Proc rate incorrect

### ISSUE THREAD

**Issue by Jimmy469** [simulationcraft/simc#3456]
Simc version 715-02 git build 4663516 has the wrong proc rates for Convergence of Fates for retribution paladins.

Per hotfix notes from 1/23/17:
Retribution Paladin
with Avenging Wrath: +250% proc rate
with Crusade: +25% proc rate

Pre-hotfix proc rate was 1.2RPPM. Post hotfix would be
with Avenging Wrath: 4.2
with Crusade: 1.5

Commit https://github.com/simulationcraft/simc/commit/881781229c25636a0c608e527d3008ea6602db93 changed retribution proc rate to 3.0 incorrectly.

Commit https://github.com/simulationcraft/simc/commit/90601f69ac02df34e0ad4adbd3d0b69c530c6d76 properly modifies the proc rate with crusade to 1.5 from 3.0. However since the base proc rate should be changed to 4.2, the modifier should also be changed to (1.5/4.2)

**Comment by Collisionc** [comment]
Yeah, I was working on fixing all the specs -- https://github.com/simulationcraft/simc/commit/2abd45e2de8f8351c59841bff8b29cffa3cbfd38 should be correct, I added in a large comment on how I came to the values I got for ret.

Are you sure that it should be 4.2 with avenging wrath? If they applied the hotfixes consistently, it should be 1.2 * 2.5 = 3

**Comment by Jimmy469** [comment]
I think we should seek clarity on what "+250% proc rate" means. As I see it, +250% from 1.2 should be
1.2 + (1.2 * 250%) = 4.2

Similarly, +25% means
1.2 + (1.2 * 25%) = 1.5

That's consistent with the snippet that blizzard posted afterwards:
Note: This change should bring Convergence back to roughly its original effectiveness for Ret Paladins who are not using Crusade.

Before any changes, the trinket was 4.2RPPM for ret.

I can try some testing after my raid tonight and see.

**Comment by Collisionc** [comment]
It's possible that ret is a special case, so if you can hit a dummy for a while and find out that'd be great. 

The only reason I think it's 1.2 * 2.5 is because of the DK note:

Frost Death Knight
with Empower Rune Weapon: +10% proc rate

In spelldata pulled from the client, the rppm of Frost for CoF went up exactly 10% in the method of 6.0 * 1.1 = 6.6

**Comment by Jimmy469** [comment]
Here's logs of my testing: https://www.warcraftlogs.com/reports/cwm9DJfxgtQAbykM/#type=auras&ability=31884&view=events

I used AW on CD (using DP talent so no crusade). Times were:
00:01.7
01:43.4
03:08.8
04:34.0
06:04.3
07:24.9
08:54.9

Which leads to CDs of:
1:42 (4 procs)
1:25 (7 procs)
1:25 (7 procs)
1:30 (6 procs)
1:20 (8 procs)
1:30 (6 procs)

Total of 38 procs over 9 minutes, or right about 4.2 procs per minute.

Also, I think 4.2 is consistent with the way the changes were worded. In the case of the frost, the new PPM is (old * 1 + buff%). It's just a bit weird since only ret that has buff% > 100%.

**Comment by Collisionc** [comment]
Unfortunately you really need about an hour of testing to get useful data due to how rppm works, which sucks with this trinket because you can't just afk autoattack a boss as I don't think the combat log says anything about the trinket proccing. :\ 

I'll probably still change it to 4.2, I just wish blizz would be like "hay guyz this is the rppm".

**Comment by krousey** [comment]
I don't see any inconsistency between the way @Jimmy469 got 4.2 for ret and the way you got 6.6 for frost.

+10% means 100% + 10% or multiply by 1.1. `6 * 1.1 = 6.6`

+250% mean 100% + 250% or multiply by 3.5. `1.2 * 3.5 = 4.2`

**Comment by navv1234** [comment]
Agreed, indeed it does. The problem is though, when blizzard hot-fixed this newest changes to the data, every hot-fixed value aligns with what they said in the post (where we could see it), except for .. Retribution paladins.

For Retribution Paladins, if we compare the data we have for the client for the Avenging Wrath case (i.e., the non talented one), we actually see that they did not do +250%, they actually did +150% (i.e., 1.2 * (1+ 1.5)). The talent-specific data does not show to the client in any way.

Which one is correct though, is anyone's guess. When I adjusted the stuff to actually be correctly applied for the talented cases, I also initially set it to 4.2, but once I looked at specifically the hot-fixed data, I also came to the conclusion that it is more likely to be 3, instead of 4.2.

**Comment by Jimmy469** [comment]
I'll try to find some time to set up a macro to hit a dummy for an hour or so while hitting AW on CD. We should be able to extract the approx # of procs based on # of wings casts. I probably won't have time to do this for a few days, though.

**Comment by Thordros** [comment]
[Here's an event log](https://www.warcraftlogs.com/reports/WbqC49txRF3j8JAM#view=events&type=auras&ability=31884) of a little over two hours of hitting abilities on cooldown, with [a LFR Convergence of Fates](http://www.wowhead.com/item=140806/convergence-of-fates&bonus=3520) equipped. I did not take Crusade, and my haste at the time of the test was 8598 (22.93%).

[Here's a paste](http://pastebin.com/JFXBBW47) of the intervals between Avenging Wrath uses over the period.

Let me know if you need any more data.

**Comment by Collisionc** [comment]
That's a pretty strong case for 4.2 being the baseline, I will adjust.

**Comment by Collisionc** [comment]
Ok, fixed.
