### ISSUE TITLE
Why doesn't the DPS data in the ability add up?

### ISSUE THREAD

**Issue by Xiadalei** [simulationcraft/simc#3570]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
that would be https://github.com/simulationcraft/simc/commit/327f040843f98e23bd419f2aa512521cd431b278
But I didn't compile the source code, I get it from http://downloads.simulationcraft.org/?C=M;O=D 
win64 version

#### simc_gui.simc file or contents

[simc_gui.zip](https://github.com/simulationcraft/simc/files/792447/simc_gui.zip)

#### Reproduction Steps:

Just use stomp so you can see the number would be like this:
![default](https://cloud.githubusercontent.com/assets/16681099/23200026/f5cb6e32-f90c-11e6-8080-cb1e1b95ad60.png)

I know it happens with TitanThunder with the overlap from multiple sources of damage. but stomp is nothing like that.
So which is right the total number or melee+stomp?

**Comment by nuoHep** [comment]
I believe this is because of the "transient" nature of Dire Beasts (as in they are not permanent pets) where the ability dps is calculated over a bigger time window (the "active" time of the pet basically) than the actual uptime of the pet.

You can see pretty much the same on a Demo Warlock's Doomguard (looking at t19m_nh) where it has ~213k Doom Bolt dps but the actual pet dps is only ~36k over the whole fight.

Stomp is basically the same (with a caveat that we aggregate all dire beasts & their actions under a single "action" so we don't even have a separate Dire Beast pet in the report).

**Comment by Xiadalei** [comment]
So basically the amount of DPS under this situation is not accurate and cannot be trusted, right?
While the percentage of the DPS is still accurate. This is weird, and suggests different calculations are used here. 
Still I do believe this issue is covered and will close this.
Thank @nuoHep for your answer. It is helpful.
