### ISSUE TITLE
Missing Hunter Pets

### ISSUE THREAD

**Issue by HnyBear** [simulationcraft/simc#3573]
SC Ver: simc-715-01-win64

I looked through the sc_hunter.cpp and didn't find the following pets.

Quilen
Cranes
Water Strider

**Comment by nuoHep** [comment]
That's because pet family is parsed in the util code (re: sc_hunter.cpp) and we don't even have the corresponding enums.

And in any case pet families are completely irrelevant now. Even Chimeara's Froststorm Breath (one of the 2 "dps" specials left alongside Worm's Burrow Attack) is not hooked up because it's a straight dps loss (and burrow is even worse). Survival having Carrion Bird by default is simply "historical" (there was a short time when specials did matter for Hunting Companion procs).

I was actually thinking about completely nuking pet family handling code from the hunter module because it's completely pointless now.

**Comment by HnyBear** [comment]
Ok, sounds good. Thank you.
