### ISSUE TITLE
Draught of Souls cooldown not recognized 

### ISSUE THREAD

**Issue by Maive23** [simulationcraft/simc#3676]
SimulationCraft 715-01

SimulationCraft is not recognizing Draught of Souls' cooldown.  I tried to add a line of text to my APL such that Vendetta (I am an Assassin Rogue) would only be used when Draught of Souls has no more than 20 seconds left on its cooldown.  The full line of text ended up looking like this:

actions.cds+=/vendetta,if=!talent.exsanguinate.enabled&energy.deficit>=88-!talent.venom_rush.enabled*10&cooldown.draught_of_souls.remains<=20

The last line (&cooldown.draught_of_souls.remains<=20) was not being taken into account in the simulation, Vendetta was being used regardless of the cooldown left on Draught of Souls.  It seems to me that SimulationCraft isn't recogizing Draught of Souls as having a cooldown since it is an item and not an ability.

**Comment by lgkern** [comment]
That's because trinket cooldowns aren't automatically added to all classes. If you want to track the CD from Draught specifically, you would need to add it to the rogue module. However, you can check the cooldown from both trinkets using 
trinket.cooldown.remains<=20
which will be true if a trinket with a CD have 20 or less seconds remaining on its CD.

Edit: That's actually really old code and *might* not work. If you could test it, we would appreciate it!

**Comment by navv1234** [comment]
Closing this for now. Reply back if the trinket-specific expressions don't work.
