### ISSUE TITLE
MULTIPLE issues #

### ISSUE THREAD

**Issue by Irongore** [simulationcraft/simc#3696]
Issue #1 I am getting errors for a ring that is extremely common amongst many specs. errors posted. I am Fury spec.
Issue #2 SimC is telling me that my weapon's item level is only 792 or whatever its telling me and that I'm using blue shit relics. the relics I'm using are current glad s3 relics etc and my weapons actual ilvl is 901.
Issue #3 When trying to import from the Warcraft website, after navigating to the search bar, you are unable to choose your character you want to import as if you have gone as far as you can go into a page. Nothing deeper to search besides a list of character names.

#### simc_gui.simc file or contents
( Pawn: v1: "Irongore": Strength=9.71, CritRating=7.54, HasteRating=10.61, MasteryRating=8.56, Versatility=8.06 )

Player Irongore attempting 'use_item' action with item 'ring_of_collapsing_futuresif=equipped.ring_of_collapsing_futures&buff.battle_cry.up&buff.enrage.up&!buff.temptation.up' which is not currently equipped.
Player Irongore attempting 'use_item' action with item 'draught_of_souls' which is not currently equipped.
Irongore missing 'use_item' action for item "ring_of_collapsing_futures" (slot=finger1)
Disable this warning by adding 'use_item' actions into the action priority list for the actor(s), or add "use_item_verification=0" to your list of options passed to Simulationcraft.
To fix issues with the target exploding <20%range due to execute, fixed_time=1 has been enabled. This gives similar results
to execute's usage in a raid sim, without taking an eternity to simulate. To disable this option, add warrior_fixed_time=0 to your sim.

**Comment by navv1234** [comment]
The ring message is just a harmless warning, and has been suppressed in recent versions.

If you are talking about the tooltips when you mouseover the artifact, that information is from wowdb. We did not have properly set up relic information in the tooltip request for the longest of time, but that has also been fixed.

As for the GUI website import, ever since Blizzard changed their website to the new layout, the "navigate to character page in armory, press import" way stopped working in a simple way. You should still be able to do it by rightclicking on the link and pressing "navigate" or "go to" or something like that (I don't recall exactly what the menu item was). This website change is the reason why we have the other battle.net import, where you select your region, server and then type in a character name.
