### ISSUE TITLE
Error 0xc000007b when starting

### ISSUE THREAD

**Issue by Nalev** [simulationcraft/simc#3736]
7.2 release 1

[DxDiag.txt](https://github.com/simulationcraft/simc/files/967031/DxDiag.txt)

Couldn't get a proper solution online, reinstalled several versions of Simc, ran as admin, etc. etc. still doesn't want to start.

**Comment by smtips** [comment]
Error 0xc000007b is a windows error. Not a program error. Not sure how techy you are but I just did a search on Error 0xc000007b only, and from the 3 or 4 articles I went and looked at it's probably a disk issue or something with Windows system files (corrupted registry entry, bad .dll file, could be a number of things). Could run check disk. 
One good description of this error: "The 0xc000007b error may be caused by windows system files damage." 
A solution also might be to restore your computer to an earlier time, it's fairly easy in windows if you have the backup partition.
Might actually do to reinstall windows. Do backups first of course. This one is hard to track down from all I've seen. Try to run some system checker and repair tools (I'm not going to recommend any even though I know quite a few, not taking any responsibility for what windows repair tools do :) ). Otherwise if you put more than a couple hours into screwing with it and still haven't found what caused the error, then I'd reinstall windows, saves a lot of time and headache in the long run. 
In any case, _SimCraft is not the cause of this error_; to repeat myself, this is a WINDOWS ERROR. Which is probably why noone has responded to you from the simcraft team.
