### ISSUE TITLE
Simcraft crashing when trying to sim

### ISSUE THREAD

**Issue by Metalich** [simulationcraft/simc#3765]
When i try to use Simulationcraft now, it crashes near the end. 
In the past i have had no issues with the program, but after getting a new graphics card, it has started to crash right before it can finish simulating.

#### Simulationcraft Version
Version 720-02

#### If Simulationcraft is crashing, please include your dxdiag file.
[DxDiag.txt](https://github.com/simulationcraft/simc/files/1014188/DxDiag.txt)

#### simc_gui.simc file or contents
[simc_gui.simc.txt](https://github.com/simulationcraft/simc/files/1014193/simc_gui.simc.txt)

#### Reproduction Steps:
Trying to sim any character causes Simulationcraft to crash near the end of the simulation, no real steps needed for me to reproduce this issue.

**Comment by Metalich** [comment]
If you need anything else to help me fix this issue, please tell me what and i'll do what i can. Much appreciated.

**Comment by Collisionc** [comment]
Looks like it's due to - nvoglv64 - which is an nvidia video driver. Try running  http://www.guru3d.com/files-details/display-driver-uninstaller-download.html and then reinstall new video card drivers to see if that resolves the issue. 

If that doesn't fix it, try https://github.com/simulationcraft/simc/wiki/CommonIssues - option 3, even though it states that it's for crashes on the start of simcraft sometimes it resolves crashes at the end of a simulation as well.

**Comment by Collisionc** [comment]
Your windows install could have some corrupt files as well, as it looks like some of the windows store apps are crashing as well. 

try running these 2 commands in an administrator command prompt - ![admin cmd prompt](http://collision.heroicstrike.org/2017-05-23_20-19-44.png)

sfc /scannow 
dism /online /cleanup-image /restorehealth

Just run them one at a time and see if it finds any problems and/or fixes them.

**Comment by Metalich** [comment]
Seemed like it was the graphics driver as your first post said. Did a clean install and it works excellent now. Thanks for the help!
