### ISSUE TITLE
Only the artifact's window open 

### ISSUE THREAD

**Issue by XYhunterZ** [simulationcraft/simc#3795]
Hello ; i've just downloaded simulationcraft and when i use the command /simc there is only the artifact's window that open . What should i do ?

**Comment by XYhunterZ** [comment]
Someone have a solution ?

**Comment by AlexanderKenny** [comment]
You likely would be better off using the project page for the addon itself since it appears that's what you are having issues with: https://github.com/simulationcraft/simc-addon However when you report it over there you will want to include whatever lua error is popping up if the output window is not. It will be impossible to diagnose your issue without it. 

As with most things if you have not already try uninstalling and reinstalling the addon as well as it may fix itself.
