### ISSUE TITLE
PVP gear not scaling with local source

### ISSUE THREAD

**Issue by Thudderson** [simulationcraft/simc#3838]
Hello, 

I am trying to sim my character who has some pvp gear equipped at ilvl 910 - the gear when I look at the results list is shown as 840 ilvl and "source" displays as wowhead rather than local. I imported my character using the simc addon so am unsure as to why this would require wowhead as a source. I have tried manually rejigging stats to compensate for the issue but can't get them right. Any help would be appreciated. If I can go into the import and manually dictate the item stats and secondaries that would be enough - if there is an easy way to do this I apologise.

Simulationcraft version 720-02

**Comment by AlexanderKenny** [comment]
First off you likely want to transition to a 7.2.5 client for simming for the current live game as you're still on a 7.2 one. The nightly builds can be found here: http://downloads.simulationcraft.org/?C=M;O=D

That said is the text display in the gear section displaying the incorrect ilvl as well or just the wowhead tooltip? It's possible both are incorrect though typically these types of errors are just wowhead displaying the incorrect tooltip (only the text output below is relevant as far as SimC is concerned).

If the text is also incorrect you can use the ilevel=x flag on each piece to manually override the ilvl of it and scale the stats accordingly. Simply add a comma to the end of that gear pieces line on your simulate tab and then add the flag with x set to whatever integer you want (910 in this case).

**Comment by Siderbas** [comment]
It is showing the wrong ilvl but the correct wowhead tooltip and is missing its secondary stats

![simcbug](https://user-images.githubusercontent.com/1843515/27277203-d6b04392-54dd-11e7-8b0a-1dcac64cf9e6.jpg)

even if i add ilevel=880. 
![2](https://user-images.githubusercontent.com/1843515/27277406-733727bc-54de-11e7-8f35-b9e95d0d53dc.jpg)


same with the trinket, added ilevel=880 and it only shows +1666int in the output instead of 1713

EDIT: Seems to be working correctly in built 725.01
