### ISSUE TITLE
[Retribution Paladin] Issue with talent build and APL

### ISSUE THREAD

**Issue by WitcherHammer** [simulationcraft/simc#3871]
Simulationcraft Version: 720-02
On the official website In all raid results for Legion 7.2.5 for Retri Paladin like
(Paladin_Retribution_T20M : 1235389 dps,  Paladin_Retribution_T20H : 1076755 dps, Paladin_Retribution_T19M_NH : 848035 dps)
we can see in the "Talents" on 5 tier the "Justicar's Vengeance" as main choose. And in APL we can notice  priority of "Justicar's Vengeance" but when you open the "Charts" window you willn't find information about damage dealt from "Justicar's Vengeance"
So, there is two possible issues:
1. The "Charts" window works wrong.
2. The APL for "Justicar's Vengeance" is written wrong.
I'm not a prof in SimCraft and may be I made a simple mistake and didn't get right result.
Please help.
P.S. I think that the talent "The Fires of Justice" will work better with "Justicar's Vengeance" than "Zeal"
and may be  it wiil be very interesting not to use "Templar's Verdict" at all and try to use only "Justicar's Vengeance"

**Comment by lgkern** [comment]
Can you try to see if the issue persists with 725-01?

**Comment by WitcherHammer** [comment]
This problem still exist on 725-01 :-(
http://www.simulationcraft.org/reports/Raid_T20M.html   - look at this raid results for 940 ilevel for retri paladin and you will see this issue too. "Justicar's Vengeance" chosen as talent but in charts there is no info about damage from this skill (

**Comment by lgkern** [comment]
Hey, talking around on discord we narrowed down the APL. The reason it isn't using the talent is because it will be never used (focusing only on DPS) if you have Whisper of the Nathrezim, which the actor has. The talent is picked simply because there are no other real DPS options in the row.

**Comment by WitcherHammer** [comment]
Not all paladins use this item.....
So, have you ever try to change APL for using this talent?  Have you ever make test of efficiency of "Justicar's Vengeance"?
2x damage under stun, healing possibility.... Is this talent so bad that you didn't include APL of him?
Can you help me to change APL if I want to use this talent, because it's hard for me I'm not a prof in Simcraft(

**Comment by lgkern** [comment]
The talent **is** on the APL, just isn't triggered on the T20M stacking raid because that paladin is using the cloak. These are the lines that it will use it:
`justicars_vengeance,if=debuff.judgment.up&buff.divine_purpose.up&buff.divine_purpose.remains<gcd*2&!equipped.137020`
`justicars_vengeance,if=debuff.judgment.up&holy_power>=5&buff.divine_purpose.react&!equipped.137020`
...
`justicars_vengeance,if=debuff.judgment.up&buff.divine_purpose.react&!equipped.137020`

So it will use it when:
-Judgement debuff is up, Divine Purpose is up and Divine Purpose will last more 2 GCDs
OR
-Judgement debuff is up, Holy Power >= 5 and Divine Purpose proc'd
OR
-Judgement debuff is up and Divine Purpose proc'd 

All conditions also require that you don't have the cloak.
The first two conditions are high up in the APL, the third one is lower in priority, you can check the ordering in the Action Priority List in the T20M report.

**Comment by WitcherHammer** [comment]
O, thank you very much)
But what I willI do if I want to make a test Justicar's Vengeance+Crusade (on 7 tier, not Divine Purpose)?

**Comment by WitcherHammer** [comment]
I wrote 
actions.priority+=/justicars_vengeance,if=debuff.judgment.up
actions.priority+=/justicars_vengeance,if=debuff.judgment.up&holy_power>=5
but I can't make a condition to strike with Justicar's Vengeance after Hammer of Justice (stun) usage. Is it possible to make this condition? Because it will increase dmg from this ability in 2 times, so final DPS will grow.
