### ISSUE TITLE
Player Skill -- recommend removal from default GUI.

### ISSUE THREAD

**Issue by Hekili** [simulationcraft/simc#3889]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version

All current versions, 7.2.5 and future.

#### If Simulationcraft is crashing, please include your dxdiag file - Instructions here - https://us.battle.net/support/en/article/Obtaining-System-Files

Not applicable.

#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

Not applicable.

#### Reproduction Steps:

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

One of the frequent issues seen in the WoW Discords is confusion when someone decides to "be humble" and turns down Player Skill.  This results in random abilities being used and a massive performance drop.

If a "Player Skill" statistic needs to be presented to the player in default reports, I'd recommend providing a result showing -X stddevs from the average as player skill is decreased.  Or that "Player Skill" should be a function of reduced reaction time.  Not random usage of abilities.

**Comment by lgkern** [comment]
Should be removed as in https://github.com/simulationcraft/simc/commit/0c170e4d09504119117faf39cf5830dce95508b3

**Comment by ubersonic** [comment]
Are you serious? And what are the good/average players supposed to use to sim our chars if you make SC just for the top 1% of players???

I came here looking to report a bug and find it was a deliberate mistake? Way to make your program useless to 99% of players >.> I may as well just go to maxdps.com now :(

**Comment by Zarggg** [comment]
@ubersonic: You seem to be under a misconception of what SimulationCraft actually *does*. It follows a given APL (Action Priority List) that represents a theoretical "best rotation" for a given class to output potential DPS for a given character build (talents, gear, etc). These simulations can be further be used to establish the impact a specific primary or secondary stat has on a player's output.

It's not just for "the top 1% of players".

**Comment by ubersonic** [comment]
> You seem to be under a misconception of what SimulationCraft actually does.

I know what it does, my issue is that it doesn't matter HOW it get it's results what matters is how accurate/useful they are, and the fact remains that the results generated using the "good" setting are (for the majority of players) more accurate and useful than the ones generated using the "elite" setting.  Be removing the option to change it the developers have made the results generated by the program either erroneous or useless for the majority of players.

Users shouldn't have to use additional commands to force the application to use the "good" setting in order to get the correct output, it should be an option like it always has been.

That is my issue.
