### ISSUE TITLE
Simcraft doesn't seem to be registering rage regen for Ceann-ar Charger

### ISSUE THREAD

**Issue by Tdildo23** [simulationcraft/simc#3918]
Please include a brief overview of the issue in the title above, as well as completing the following:

latest version downloaded today.

When looking at the sample rotation, it does not seem to be including the rage generated by Ceann-ar charger.

For example after using battle cry, it has Raging blow, odyns fury, blood thirst, then I am only at 67 Rage. whereas when I hit this on a dummy, I hit nearly 100 rage after blood thirst (after auto attack about half a second later I hit 100 rage). 

If you look at the sample table it finishes with a second raging blow ending at 97 rage. If you subtract that 10 rage generated by raging blow crit, you would have 87 + the 16 I should have generated from Enraging (via the helm) from rampage and the Bloodthirst  crit I would be at 100. So it adds up.

I think the sim is not measuring the helm's rage regeneration, and I think not only does this mess up DPS, but it also then distorts the stat weights, because with that extra rage regeneration haste becomes less meaningful.

**Comment by penguinlust** [comment]
I'm assuming the bug is in the "Sample Sequence Table". From what I can tell, the bug is only in this listing, and the Ceann-ar Charger is fine. However, it looks like auto_attack is what's broken -- it only fires once.

When I run the most recent OS X nightly build (as of 23 Nov 2017) on my warrior (who has Ceann-ar Charger equipped), I end up with a sample sequence of:

0124568BCMLNMLPMWYaWXYWaYXWYaWYXWYaWYXWYaADLMP8LMNLMYWaYZXYWaYWXYWaYZaXWYaZCMPLMP8LXYWaYWXYWaYBZaYWaYAD9LMNLMPWXYWaYZa8XWYaWYXWYaWXYWaYWaADLMPLMPWXYWaYXW8YaZYXWYXWCMBNLMPLXYWaYWXYWaYWXYW8aYWADMLMPLMYWaYWXYWaYWXYWaYWXYWaYZ8ADMLMNLMYWaYXWYQRRRRRRRTRUTRRRTCKKJKKJKRR8RRRTRSRTRUTBRUTRUTCKKJKKJKRRRTR

where 5 is auto_attack. Notice it only fires once. And going through the table that's the only time it generates rage. Now mind you, things look correct everywhere else in the simulation.

I don't have the code available to check right now (I'm on the road), but I suspect we'd find only the sample sequence report itself is what's wrong.

**Comment by Archimtiros** [comment]
Whatever issue there might have been is no longer relevant in BfA. The sample sequence table is reporting rage generated from both Ceann-ar Charger and auto-attacks correctly.

The sample sequence table only shows actions, not periodic events (auto attacks, individual dot ticks). The auto-attack action at the top only shows the simulation starting that action (enabling/beginning auto attacks), but they're still happening over time and the rage reported in the sample still includes them,
