### ISSUE TITLE
Scale factors

### ISSUE THREAD

**Issue by Ragatokk** [simulationcraft/simc#3956]
Hello, I would love it if people were able to add in their own scale factors.
If it is already possible, please tell me how to :)

For DK tank, I would want a scale factor that works much like DTPS, just it also treats part (ish 80%) of the HPS as damage not taken and I would also give a bit of credence to the TMI as not taking spiky damage is also important. Valueing tmi at 30% and this other factor at 70% 

Also, is there a way to scale for MSD? (max spike damage)
For example, for warriors MSD is a major issue so it would be nice to know.
If I could do that I would much rather use that instead of tmi in the formula suggested above.

**Comment by lgkern** [comment]
Hello, everyone is welcome to contribute to the project as they believe would be benefitial. Don't be afraid to implement it and send a pull request for us to review.

**Comment by scamille** [comment]
There already is a extensive tank metric called TMI (see https://github.com/simulationcraft/simc/wiki/SimcForTanks and http://www.sacredduty.net/theck-meloree-index-standard-reference-document/) developed in the past by Theck.

The problem is a lack of support/maintenance for a lot of tank things right now in SimC. If you want to join the team and bring tank simulations back to the spotlight, just contact us on Discord.
