### ISSUE TITLE
Crucible format

### ISSUE THREAD

**Issue by ghost** [simulationcraft/simc#3997]
so i been having this error

Simulation runtime error:
Player ---- invalid crucible format, expected: power_id:rank[:power_id:rank...] Player ---- invalid crucible format, expected: power_id:rank[:power_id:rank...]

**Comment by navv1234** [comment]
You have a couple of options:

1) If you are on MacOS, you can download http://downloads.simulationcraft.org/simc-730-02-osx-x86.dmg, which supports the new crucible= option format
2) Otherwise, you can install the latest nightly build for windows from http://downloads.simulationcraft.org/?C=M;O=D 
3) Or, you can install an earlier version of the simulationcraft addon that will export the earlier version (1.8.1) of the crucible string

We will do an official release soon.

**Comment by ghost** [comment]
ok 701-02 worked tnx :)
