### ISSUE TITLE
Regression problem for empty parameters

### ISSUE THREAD

**Issue by Bloodmallet** [simulationcraft/simc#4126]
Since https://github.com/simulationcraft/simc/commit/ea358b72d0c54471f8e6bed5540462152743faf3 empty parameters like `threads=` no longer work, but create `ERROR! Setup failure: invalid stoi argument` or more recently `ERROR! Setup failure: Could not parse option 'threads' with value '': invalid stoi argument`. Previously an empty threads argument triggered simc to use all available threads.

This regression can be seen wherever one previously could leave empty values. Another example would be items. `trinket1=,id=,ilevel=860` worked previously and set that trinket to no trinket. Now simulationcraft errors out.

@scamille I'm cc you because the mentioned commit that changed this behaviour comes from you. Would it be possible to recreate the previous behaviour?

**Comment by scamille** [comment]
The idea was to more strictly enforce a correct input (in this case, an integer), instead of silently converting eg. trinket1=,id=2929l,ilevel=860 to a id of 0.
There were and still are a lot of places where SimC silently accepts invalid str to number conversions, just because it would be tedious to do otherwise with the libc functions providing silent failure to 0 by default.


I would personally not want to revert to the previous behavior, and expect valid inputs, in this case 0.

If we insist on bringing the old behavior back, we can do so either again letting things convert silently or at least provide warnings.

**Comment by scamille** [comment]
Just to make this clear as well:
trinket1=,id=0,ilevel=860 still works.

We could also make empty strings "" a special case allowed to silently convert to a magic number, in this case 0, and still fail on eg. id=2929l loudly.

**Comment by Bloodmallet** [comment]
While I understand the need to transition to stricter input checks, I think some auto conversions were pretty handy. Empty to default values was intuitive and at least to me empty `threads` to max threads was in that group too.
I think empty strings are a good addition. I don't know about others but if I see a profile and and want to run that profile, but want to overwrite it in a way that creates an empty slot instead of using a different item, the empty `id` would be the intuitive way to me again. While `id=0` certainly makes sense after hearing about it, I don't see how that is intuitive for someone new. And I'm quite sure that I wouldn't be able to "find" this.

Showing warnings and teaching the user how to do something properly is a great idea, though.

**Comment by scamille** [comment]
I must say that I wasn't aware that empty numeric arguments were such a relied upon feature. So sorry for just so silently breaking this.

Converting a empty input string to 0, but failing on other invalid non-empty input is a good solution/compromise here. I'll change it.
