### ISSUE TITLE
Outlaw Rogue RTB

### ISSUE THREAD

**Issue by Prophet001** [simulationcraft/simc#4217]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
73002
#### simc_gui.simc file or contents
This file is saved in the same folder as the program after each simulation. Make sure to run the simulation that is giving you issues, then include the file here by either uploading to github, copy/pasting the contents, or using http://pastebin.com/

#### Reproduction Steps:
There is no bug but a question about the priority list for outlaw. The sim will reroll if you have a single true bearing buff and nothing else. I understood that you always wanted to keep true bearing. Is this confirmed to be correct?

Please include any other steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

**Comment by Mystler** [comment]
Assuming you have the latest simc version this is the rerolling rule in use ```actions=variable,name=rtb_reroll,value=!talent.slice_and_dice.enabled&buff.loaded_dice.up&(rtb_buffs<2|(rtb_buffs<4&!buff.true_bearing.up))```. To put it into words, you want to re-roll only if Loaded Dice is up *and* you have only one buff / less than four without True Bearing. And yes, this means that with only one TB buff and Loaded Dice up you still re-roll because you will get two guaranteed.
