### ISSUE TITLE
Frost Mage list possible improvement

### ISSUE THREAD

**Issue by akis-t** [simulationcraft/simc#4218]
Please include a brief overview of the issue in the title above, as well as completing the following:

Simulationcraft Version 730-02

Frost Mage default profile script stripped down for clarity. 

I am not an expert script writer but the below script gives very good results for a Frost Mage - 100K extra DPS on single target, from 770K to 870K. Talents are as follows:

talents=https://worldofwarcraft.com/en-gb/game/talent-calculator#mage/frost/talents=2133122
artifact=53:0:0:0:0:783:1:784:4:785:4:786:4:787:4:788:4:789:4:790:4:791:4:792:4:793:1:794:1:795:1:796:1:797:1:798:1:1296:1:1373:1:1537:4:1538:1:1539:1:1540:16:1641:1

actions=call_action_list,name=single2

actions.single2=variable,name=fof_react,value=buff.fingers_of_frost.react
actions.single2+=/variable,name=brain_freeze_react,value=buff.brain_freeze.react

# start

# flurry always followed by ice lance
actions.single2+=/ice_lance,if=prev.flurry

# GS always followed by Flurry if BF is on
actions.single2+=/flurry,if=variable.brain_freeze_react&prev.glacial_spike

# FB followed by Flurry if BF is on and a GS is not soon to come
actions.single2+=/flurry,if=prev.frostbolt&variable.brain_freeze_react&buff.icicles.stack<=3

# IV whenever 
actions.single2+=/icy_veins,if=buff.icy_veins.down

# ebonbolt will trigger BF so cast it only when BF is down
actions.single2+=/ebonbolt,if=variable.brain_freeze_react=0

# GS with BF seems to be slightly better than whenever available
actions.single2+=/glacial_spike,if=variable.brain_freeze_react
#actions.single2+=/glacial_spike

# IL if FoF is up
actions.single2+=/ice_lance,if=buff.fingers_of_frost.stack>0

# Frozen Orb whenever we can
actions.single2+=/frozen_orb

# nothing else so cast FB
actions.single2+=/frostbolt

**Comment by vituscze** [comment]
The default APL is already doing almost all these in roughly the same order. The only differences are GS only when you have BF up (which is a gain/loss depending on stats, legendaries and set bonuses) and using `stack` for the Ice Lance action (which is unrealistic, since most Fingers of Frost are random and thus require a reaction time).

I'm not sure where the 100k difference is coming from. Comparing your APL against the default profile, I'm getting 2.4% loss. https://www.raidbots.com/simbot/report/jsfi9QMSkdKYYKw7qoXma3

If you have the full profiles, please add them so that I can take a look.

**Comment by akis-t** [comment]
Sorry my mistake, I had omitted Icy Veins from the default script as I was taking out / stripping out everything else. Thank you for looking at it.
