### ISSUE TITLE
Cant find anything on Sephuz? 

### ISSUE THREAD

**Issue by Vardelox** [simulationcraft/simc#4265]
I have been trying to sim my pally but for some reason I cant seem to find any info for sephuz anywhere? Specifically when it procs and how much the dps increases when I get it to proc through out a fight. I don't know if im missing something or I have my profile set up wrong. I have searched for answers but all the answers I have found have been vague. 

Here is my character if it helps. 
# SimC Addon 1.9.0

paladin="Åsmund"
level=110
race=blood_elf
region=us
server=area_52
role=tank
professions=mining=771/skinning=800
talents=2132132
spec=protection
artifact=49:0:0:0:0:1646:1:1378:1:1135:1:1134:1:1133:1:1132:1:1131:1:1130:1:1129:4:1128:4:1127:4:1343:1:1126:4:1125:4:1557:4:1558:1:1559:1:1560:24:1124:4:1123:4:1122:4:1121:4:1120:1
crucible=1739:1782:1128/1739:1778:1125/1739:1782:1124

head=,id=152151,bonus_id=3610/1487/3337
neck=,id=134529,enchant_id=5439,bonus_id=3536/1612/3337
shoulder=,id=142201,bonus_id=3535/1572/3337
back=,id=152149,enchant_id=5434,bonus_id=3610/1472/3528
chest=,id=152148,gem_id=151583,bonus_id=3610/1808/1472/3528
shirt=,id=3428
tabard=,id=52252
wrist=,id=152281,bonus_id=3610/1472/3528
hands=,id=152150,bonus_id=3610/1472/3528
waist=,id=142129,bonus_id=3418/1552/3337
legs=,id=137070,bonus_id=1811/3630
feet=,id=139241,bonus_id=3417/1582/3337
finger1=,id=134489,enchant_id=5428,bonus_id=3536/1612/3337
finger2=,id=132452,enchant_id=5428,gem_id=151583,bonus_id=3459/3630
trinket1=,id=142167,bonus_id=3573/40/1522/3528
trinket2=,id=128711,bonus_id=689/600/679
main_hand=,id=128867
off_hand=,id=128866,gem_id=152043/137543/152025,bonus_id=736,relic_id=3610:1472:3528/3535:1607:3337/3611:1517:3337

**Comment by lgkern** [comment]
Hello, Sephuz is implemented on a class-by-class case. For the paladin module ( https://github.com/simulationcraft/simc/blob/legion-dev/engine/class_modules/sc_paladin.cpp ) it seems that it is only implemented to proc from Rebuke (unless I'm missing some triggers). So the effect would only happen if you're simulating casting_patchwerk, otherwise, it will never occur.

**Comment by Melekus** [comment]
Hello, it's actually a bit more complicated than this for protection paladin : rebuke is not in the action priority list so you would have to add it yourself.
The process for that is simple, find the default profile for protection paladin T21 (either through the GUI in sample profiles or in the folder under profiles/Tier21/T21_Paladin_Protection.simc and copy the APL (everything after the crucible section and before the gear section) at the end of your simc input.
Once that step is done, add the following line after actions=auto_attack : 
actions+=/rebuke 

Now that your character use their interrupt spell in the simulation, you need to setup a casting event. Fortunately for you, tank dummies actually have casting events built in by default so instead of using the casting patchwerk fight style you can just use the usual Patchwerk. If you want to sim without any sephuz proc in the fight you will have to remove rebuke from the APL again.
