### ISSUE TITLE
Updated release version long overdue

### ISSUE THREAD

**Issue by penguinlust** [simulationcraft/simc#4272]
The hasn't been a release version since 730-2 -- almost 5 months ago. We skipped over 7.3.2 and are now on 7.3.5. Many bugs have been fixed and data modified. Most of the class balance adjustments are done and four new races have been added. It's time to update the release version. 

#### Simulationcraft Version
730-2

#### simc_gui.simc file or contents
NA

#### Reproduction Steps:

go to www.simulationcraft.org/download.html. The latest release available is release-730-02 dated 14 Sep 2017

**Comment by Melekus** [comment]
There is indeed no new release, but for the time being you can download the latest nightly versions here : http://downloads.simulationcraft.org/?C=M;O=D

**Comment by penguinlust** [comment]
That's not the point. I know that, you know that, but a lot of people only download the release versions. How many bugs have we seen in the last couple of months about bad item data alone?

It doesn't help that the published dps numbers on the home page list it as 7.3.2 when we're on 7.3.5.

**Comment by scamille** [comment]
It's good to have this discussion here going into bfa-dev. Maybe we want to only have automated releases in the future, removing the burden of manually setting/publishing releases? This can have some disadvantages in itself, but might still be the better solution.

I'm sure our two current release publishers (win and osx) will eventually join the discussion here. In the end they decide what happens, just because no one else does the work.

Of course we are always glad about additional manpower. So if you are interested in improving the releases, that would be another option ;)

**Comment by penguinlust** [comment]
I don't have any way to build for Windows. That said if you need a Mac OS builder I could do that.

**Comment by penguinlust** [comment]
Now that 7.3.5 release 1 is out I'm closing this
