### ISSUE TITLE
Gear comparison overrides other than specified

### ISSUE THREAD

**Issue by Vsmit** [simulationcraft/simc#4285]
SimC Version 735-02

[simc_gui.txt](https://github.com/simulationcraft/simc/files/1764902/simc_gui.txt)

When simulating for gear comparisons, using the "copy=" function, any ring specified using the "finger2" slot will also be copied into the "finger1" slot, unless both slots are specified in the comparison. Does not seem to occur with trinkets.

Example:

copy=epicring1
finger1=,id=152064,bonus_id=3611/1487/3528

copy=epicring2
finger2=,id=152064,bonus_id=3611/1487/3528

copy=legring1epic2
trinket2=,id=134204,bonus_id=3394/605/1542/3528
finger2=,id=152064,bonus_id=3611/1487/3528
finger1=,id=152626,bonus_id=1811/3630

In epicring1, the equipped ring is correctly replaced. In epicring2, both rings are replaced by the specified ring. In legring1epic2, everything is replaced correctly.

This was also an issue in version 735-01 (9fa217150), but was not noticed by me until today, at which point I updated to -02 (825bd7850).

**Comment by lgkern** [comment]
When using the copy function without providing a base profile, it will use the previous actor as base. Which means if you have
`finger1=a`
`finger2=b`
`...`
`copy=1`
`finger1=x`
`...`
`copy=2`
`finger2=x`

actor 2 will have `finger1=x` and `finger2=x` because it is overriding actor 1 instead of base.
In order to fix that you need to provide a base profile:
`druid="Layalva"`
`...`
`finger1=a`
`finger2=b`

`copy=1,"Layalva"`
`finger1=x`
`...`
`copy=2,"Layalva"`
`finger2=x`

**Comment by Vsmit** [comment]
Is this documented anywhere? The only thing I can find (in the official documentation) are passing uses of the function but without much in the way of any explanation, other than, "This makes a copy of the profile," or something similar.

**Comment by seriallos** [comment]
https://github.com/simulationcraft/simc/wiki/Characters#manual

Think the main bit it doesn't specify is that "current character" is basically the previously defined actor.

`copy` does have a second parameter to allow more granular control of which actor is used as the base for the copy:

```
armory=region,realm,character
name=base

# will only swap finger1 from base profile
copy="ring1",base
finger1=x

# will only swap finger2 from base profile
copy="ring2",base
finger2=y
```
