### ISSUE TITLE
New raid event .remains/.up expression

### ISSUE THREAD

**Issue by Juliacare** [simulationcraft/simc#4327]
Previously in this week a new expression was added which goes something like

> actions+=/<spell>,if=raid_event.name.<name>.<expression>

sadly only in, amount, duration, cooldown, exists, distance/max_distacne, min_distance and to_pct exist as expressions. 

I was hoping that remains or up could be added as an expression to flag 1 if the raid event is currently active and 0 if it is not.

**Comment by scamille** [comment]
raid event expression are currently attached to multiple raid events, since you can have multiple raid events with the same type or even with the same name.

That makes those expressions a bit more complicated to code.

My current understanding is that it would be good to have the following:
* .in: Returns the time until the next matching raid event will start.
   Edge condition: When the raid event has started and is 'up', should this return 0 or already the time the the next planned start?
Already implemented, not sure if exactly like this.

* .remains: Return the time the currently running matching raid events will be up without interruption.
Edge condition: Return 0 or negative time when the raid event is finished? Start with 0 or with timespan::min() before the first event?

* .up : Return true if a matching raid event is currently up, false otherwise.

**Comment by Juliacare** [comment]
I think .in when in the current raid event should return to the next raid event that has the same name or type and not the current. For current .up or .remains could be used.

**Comment by scamille** [comment]
What about all the remaining raid event expressions? Minimal invasive change would be to keep them in the "next raid event happening (aka .in)" section.

(duration, cooldown, distance, max_distance, min_distance, amount, to_pct, count)

**Comment by Juliacare** [comment]
As discussed on discord the current expressions are good off using the same method as the .in expression. With the BFA-dev changes this can be used on both types of events and named events. The requested .remains or .up feature would act out for the current events whilst the rest for the next upcoming.

**Comment by Juliacare** [comment]
Implomented by @scamille
