### ISSUE TITLE
unused runes in the Unholy DK profile during AoE

### ISSUE THREAD

**Issue by Pusikas** [simulationcraft/simc#4371]
Please include a brief overview of the issue in the title above, as well as completing the following:

#### Simulationcraft Version
7.3.5 and 8.0.1 nightly 7dd663fc3d

#### Reproduction Steps:

In the AoE action list, some skills are only used when `death_and_decay.ticking`.

```
# AoE rotation
actions.aoe=death_and_decay,if=cooldown.apocalypse.remains
actions.aoe+=/defile
actions.aoe+=/epidemic,if=death_and_decay.ticking&rune<2&!variable.pooling_for_gargoyle
actions.aoe+=/death_coil,if=death_and_decay.ticking&rune<2&!talent.epidemic.enabled&!variable.pooling_for_gargoyle
actions.aoe+=/scourge_strike,if=death_and_decay.ticking&cooldown.apocalypse.remains
actions.aoe+=/clawing_shadows,if=death_and_decay.ticking&cooldown.apocalypse.remains
actions.aoe+=/epidemic,if=!variable.pooling_for_gargoyle
actions.aoe+=/festering_strike,if=talent.bursting_sores.enabled&spell_targets.bursting_sores>=2&debuff.festering_wound.stack<=1
actions.aoe+=/death_coil,if=buff.sudden_doom.react&rune.deficit>=4
```

Is this intended? The above is from the latest nightly, but the last 7.3.5 profiles looked similar.

It looks to me that for example Scourge Strike would only be used 10 seconds out of 30, and only if the character does not have to move. During movement, it is even less. This would lead to the character sitting on lots of unused runes during AoE. The is no other action that would lead to using these runes in the AoE action list.

**Comment by Pusikas** [comment]
If I find other stuff with the Unholy priority lists, should I add it here, or open a new issue? Because this is problematic:
```
apocalypse,if=debuff.festering_wound.stack>=4
```

This make sense, but if you check out the AoE priority list above, you'll see that Scourge Strike is only used while Apocalypse is on CD and Festering Strike only when you're at 0 or 1 stacks of Festering Wound. This means that Apocalypse won't get used. And without Apocalypse on CD, Scourge Strike won't get used, either.

Also, Festering Strike only gets used if you have Bursting Sores talented. So depending on your talents, even with Death and Decay ticking, the character is just doing nothing, most of the time.

**Comment by Melekus** [comment]
You can check what the profile is actually performing in the html results file : a pie chart shows the time spent on each action (including waiting time) and a sample action sequence is provided under Action Priority List > Sample Sequence Table. You can clearly see that the APL doesn't have that much waiting time in aoe situations.

You make a good point though : at the moment the APL is built to go through the "aoe" list and then go on through the "generic" single target list. Even though some actions may be missing from aoe, this doesn't cause an issue because the simulation goes on through the "generic" action list if there's no valid action to perform in aoe. 

I agree that it is not an ideal solution, especially for readability.
The next iteration of the APL should hopefully have a fully fledged aoe rotation and won't call the generic action list after running through the aoe list.
