### ISSUE TITLE
Stats weight bug? Warlock

### ISSUE THREAD

**Issue by raldon00** [simulationcraft/simc#4452]
So im trying to check my stat weights (I play demonology warlock).
But when I change my "demonic calling" talent to "doom" my Haste weight goes from 0.98 to 0.24 ... That doesnt have any sense.

Also when I change some stupid talent like the lvl 90 "grimoire: Felguard" to "inner demons" haste goes from 0.95 to 0.84 ... I dont know if this is correct, but I dont see how there is that a huge diference in Haste between this 2 talents.

Im pretty sure the doom thing is a bug, and I dont know about the other one... I dont think im doing nothing wrong.

Simulationcraft version: 8.0.1, release1 (But I tried the last nightly build and i have the same problem)

This is my "simc_gui.simc" file
https://pastebin.com/C4EnAFAs

**Comment by scamille** [comment]
Something I can always recommend in such a situation:
Run a single sim with the base stat (and save its html report), then run another sim with +delta haste and also save its html report.

You then have 2 reports which you can compare in more detail, and why eg. the dps difference between the two 0.98 * delta in one case, and only 0.24 * delta with Doom.

Or maybe our warlock devs know something offhand ;-)

**Comment by raldon00** [comment]
I just tried to turn all buffs "on" (I only had arcane intellect) and that 0.3 haste value seems good now (only for changing that it went from 0.3 to 1.05).
It is still a bit worst than vers. and crit but at least now its a normal value.
So I think its fixed now (but it seems really weird that a couple buffs change the haste value that much xD)
Thanks for answering me and for the help :)

**Comment by raldon00** [comment]
Ok so today I tried to sim again, same talents, same gear, same conf.
Literally the only difference is that my neck was lvl 15 and now its lvl 16, and that I have an extra trait on my helm (+4% more speed)
For some reason, now Haste gives me a value of 0.8+ (its 0.60 more than yesterday)
So I just copied the character stats I tried to sim yesterday, and again simc gives me a 0.24 value for that.
I tried that 4 times with each one, no difference. The same gear gives me a huge difference in haste, only for 2 i lvl in neck and a mobility trait. (Again, same simulationcraft conf. and same talents)

This is "simc_gui.simc" file of the simulation of today
https://pastebin.com/9APcYmi5

**Comment by scamille** [comment]
There is always the possibility of some breakpoint in a stat. For haste that is most likely related to synchronised cooldown usage in the action priority list.
Solutions to analyse this more in depth is either doing plot simulations which lists you dps values at certain stat rating changes, or manually doing those simulations (eg. With both neck levels you mentioned) and then analyzing the differences between the two in-depth in the HTML report.

There is unlikely a bug in the core stat weight calculations in SimC, as mentioned this is usually something funky going on in the class module.

With shadowlands released I am going to close this since it will no longer be relevant for the updated warlock code.

If you ever come across such an anomaly again please.create a new ticket and hopefully the warlock team will find more time to investigate this.
