### ISSUE TITLE
Segmentation fault on guild sim

### ISSUE THREAD

**Issue by sebsoto** [simulationcraft/simc#4463]
### Describe the bug

sim_signal_handler: Segmentation fault! Iteration=1 Seed=14062129501488768573 TargetHealth=397100

*** Error in `../simc': double free or corruption (!prev): 0x00000000037c69d0 ***

### Expected behavior
I expect this sim to complete 
### To Reproduce
Running simc on this .simc file
```default_region=us
default_server=emerald-dream
fight_style=HecticAddCleave
guild=singularity,max_rank=5,cache=1

single_actor_batch=1
```
### Additional information
* SimulationCraft Version (required)
SimulationCraft 801-02 for World of Warcraft 8.0.1 bfa-BETA (wow build 26095, git build bfa-dev 5f40a49)

**Comment by scamille** [comment]
Closing this as it has been so long ago and won't be reproducable now. Sorry for not looking into this.

Multi target and movement fight style are always much more prone to crashes since they are not well tested for all specs. So the problem was likely some character in your guild with a more exotic talent combination which cause a crash in some not-perfect class implementation.

We will try to reduce this in shadowlands by having more extensive automated testing.
