### ISSUE TITLE
Evocation for Arcane Mages stop earlier than 92/97% mana

### ISSUE THREAD

**Issue by Deladox** [simulationcraft/simc#4486]
### Describe the bug
When looking at the mana graphs for arcane mages you can clearly see that after the fight starts, the mana for the mage does not go above 75%. Which, if you look for the evocation part in the code, it says "actions.burn+=/evocation,interrupt_if=mana.pct>=97|(buff.clearcasting.react&mana.pct>=92)".

### Expected behavior
Expected to see that with every evocation, the mana for the mage goes up to 97 or 92% mana.

### To Reproduce
Added that under description of the bug, you can recreate it just by simulating an arcane mage.

### Additional information
* SimulationCraft Version (required)
801-01 downloaded and 801-02 online.

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
Dont feel like this is necessary since you can very easily reproduce it yourself. Could also be that you shouldnt go over 75% with evocation, however that feels like a dps decrease.

**Comment by vituscze** [comment]
The mana graph shows average mana levels across all iterations, which is why you won't see it hit that high mana levels unless Evocation happens at the exact same time in all iterations.

If you run a single iteration sim (with iterations=1 or log=1), it should be clear that the mage is reaching (almost) full mana.
