### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by brokencomp** [simulationcraft/simc#4489]
### Describe the bug
linux compilation was working fine, today it seg faults

### To Reproduce
compile on ubuntu, it seg faults at startup

### Additional information
* SimulationCraft Version (required)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by scamille** [comment]
What Ubuntu version?
How do you compile SimulationCraft?
What crashes? Compilation, executing ./simc or ./SimulationCraft ?
Compiler version, and if you are talking about the GUI, QT version?

**Comment by brokencomp** [comment]
mint 18, using your download to compile, make 
executing SimulationCraft crashes (Segmentation fault (core dumped))

using git checkout i have traced it to a commit this morning between midnight and 0100

git rev-list bfa-dev -n 1 --first-parent --before="2018-08-29 00:00:00" --  works
git rev-list bfa-dev -n 1 --first-parent --before="2018-08-29 01:00:00" -- seg faults

**Comment by scamille** [comment]
Sorry for not replying earlier.

I think the problem is that your Mint18 g++ version is too old to compile SimulationCraft. In Theory something like GCC5 should be enough, but in practice it is something like GCC6 because of various compiler problems with C++14 in the older versions.

Our current shadowlands CI pipeline uses GCC6.5 on Ubuntu 18.04 as the lowest compiler. If you can get this version or something higher, you should be on the safe side at least for the mid term future. 

If the problem still persists, please free to open this / a new ticket again.
