### ISSUE TITLE
Simulation freezes when opening

### ISSUE THREAD

**Issue by pavlorr** [simulationcraft/simc#4490]
System: x64 W10.

Used to have Simcraft back in Legion. Uninstalled.

Re-installed today and:

1. Whenever i open it and try any tab (other than the info Tab), the application freezes and nothing responds other than closing it. Have tried multiple compatibility settings; none worked.

2. My old sims still show there even though I did a clean install. New folder, new names everything but they still show.

**Comment by KnyxPT** [comment]
Same issue here.. and im new to SimCraft...

**Comment by ganga-re** [comment]
same here. Win 10 x64

**Comment by ganga-re** [comment]
Tried with the nightly version too over the last 2 weeks. Still crashing at start

**Comment by klepp0906** [comment]
you guys ever find a fix?  My simc is crashing on open as well.  simply hangs w/ a blank white screen.

**Comment by scamille** [comment]
Sorry for not replying earlier.

Having problems with the GUI itself is often a problem with graphic drivers, or can just be a bug with the GUI Framework that we use (QT), related to your hardware.

Since this Framework has also been updated a lot, this might have fixed your problem in the meantime.

If you still have this issue, please open this again / new ticket, and we can hopefully get this better investigated.
