### ISSUE TITLE
Warrior: Seismic Wave hotfix: damage reduced by aprox 52%.

### ISSUE THREAD

**Issue by Voltsicle** [simulationcraft/simc#4500]
### Describe the bug
Tootip damage on an item level 325 shows Seismic Wave doing 847 damage. Not the 1576 Your tooltip suggests.

**Comment by Archimtiros** [comment]
The Seismic Wave hotfix was applied when it hit live servers [last Monday](https://github.com/simulationcraft/simc/commit/1c26d4da47a41b297d3e0f2c8951e22fd8fae695), and matches in game expectations.

I'm not sure what you mean by "the 1576 your tooltip suggests"; if you're referring to the tooltips in the HTML report, they're largely superfluous - those tooltips are pulled from wowdb and use whatever values are in their database, which may or may not be updated, but don't have anything to do with the simulator itself.

**Comment by JamieCoding** [comment]
The tooltips in game for seismic wave seem to be showing 15% less than the actual damage it does. My 325s show 847 tooltip damage but it actually does

947 = 871 * 1.15

and my 340s show 971 but it actually does

1117 = 971 * 1.15.

This is assuming it is reduced by armour since it's physical, I haven't double checked this yet since the Zandalar target dummies all seem to have the same armour damage reduction (30%) unlike in previous expansions. 

Edit: A quick check on the Legion target dummies suggests it is reduced by armour.

 I suspect this is related to my other post above and the fact that this is an item tooltip rather than a spell tooltip.

**Comment by Archimtiros** [comment]
Correct, all physical damage is reduced by Armor, unless specified otherwise. I don't think that's the OP's issue though, because (it sounds like) he's saying he sees a pre-nerf tooltip somewhere. My guess is that it's just pulling from wowdb which hasn't updated it's values, but without knowing what tooltip he's referring to, it's hard to say. Either way, it may be misleading, but doesn't really have anything to do with the simulator.

As for your numbers, the reason they're not adding up is because Seismic Wave is affected by the Arms scaling aura (+15%) and then reduced by armor, neither of which are reflected on the tooltip. So in effect, it's being increased by 15%, then reduced by ~30%.

**Comment by JamieCoding** [comment]
Yes sorry, I should have been a bit clearer, this is different to what the OP is referring to, I just thought I'd mention it as it was related. What exactly is the Arms scaling aura? Is it just a way for Blizzard to change all ability damage at once without doing it spell by spell?

**Comment by Archimtiros** [comment]
Correct. Every spec has a hidden aura which modifies the damage/healing of (most of) their abilities, as well as various other attributes. As you surmise, it's a way for Blizzard to balance overall spec performance without upsetting their rotation by adjusting one spell, or necessitating adjusting every spell individually.

The effects are not consistent and unique to the needs of the spec - for example, Arms has an effect increasing most ability damage by 15%, but a separate effect specifically increases Bladestorm's damage by only 12%. On the other hand, Fury has an effect which reduces the damage of auto attack by 30%, separate from the -12% modifier on regular ability damage. You can find them in SimC's SpellDataDump, or by searching the [spec class] name on wowhead/wowdb (although they're often not updated for the latest hotfix).

**Comment by JamieCoding** [comment]
Ah ok, that's really helpful, thanks!
