### ISSUE TITLE
[Arms] increase damage by spreading deep wounds opportunistically 

### ISSUE THREAD

**Issue by ssateneth** [simulationcraft/simc#4508]
I remember monk windwalker having a cycle condition to spread its mark of the crane. Why not do this to arms too?

Use sudden Death procs to opportunistically hit any target that has deep wounds remaining < Deep Wounds duration * 0.3
Use Mortal Strike to hit targets that are not in execute range and has deep wounds remaining 
 < Deep Wounds duration * 0.3 as long as your main target has deep wounds on it
Use Execute to hit targets during that are in execute range and has deep wounds remaining 
 < Deep Wounds duration * 0.3 as long as your main target has deep wounds on it

**Comment by scamille** [comment]
Thanks for your ticket.

Action Priority List is a never ending improvement process. So why not: Probably because no one has yet done it or found the time to do it for Arms.

I am sure our warrior developers will eventually take a look at it. If you want, you can also create a pull request modifying the relevant stuff in sc_warrior.cpp, which certainly makes implementation time shorter.

**Comment by scamille** [comment]
Closing this now with the new expansion.

Again, APL can probably always be improved. If you want to help with it's development reach out to us on Discord, or you can directly through a pull request here.
