### ISSUE TITLE
Initializing: No active players in sim! Mistweaver Monk

### ISSUE THREAD

**Issue by Darkinge** [simulationcraft/simc#4522]
### Describe the bug
Not able to sim my mistweaver monk.

### Expected behavior
I tried to sim my monk its not working as seen below.

### To Reproduce
Look at log.txt

### Additional information
SimulationCraft Version: 801-01

[log.txt](https://github.com/simulationcraft/simc/files/2363222/log.txt)

**Comment by Juliacare** [comment]
We have a system in place to stop people from simming unsupported specs, which is exactly what you just ran into. Mistweaver is not supported and because of that you got this error.
This system is put in place so that users will not sim and assume their results are correct when the module is unsupported so rather than risk that any unsupported spec is just not simmed, since your character is the only character in your sim it refuses to sim.

I hope this shed some light onto your issue, I'm going to close the issue as it is intended.
