### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by SveSop** [simulationcraft/simc#4581]
### Describe the bug
Pulled 59c3f2d5de3d93d87e03e77e0561518d8fcd8779 , and are not able to build.

### To Reproduce
Pull 59c3f2d5de3d93d87e03e77e0561518d8fcd8779
make clean && make distclean
qmake simcqt.pro
make

```
engine/util/fmt/format.cpp:8:10: fatal error: fmt/format-inl.h: No such file or directory
 #include "fmt/format-inl.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:1315: recipe for target 'qt/format.o' failed
make: *** [qt/format.o] Error 1
```

### Additional information
Ubuntu 18.04
`gcc (Ubuntu 8.2.0-1ubuntu2~18.04) 8.2.0`
`g++ (Ubuntu 8.2.0-1ubuntu2~18.04) 8.2.0`

**Comment by scamille** [comment]
Fixed in 5feb9d17c836b06d00ba6194ac73f3f82d1a983c

Is there anything in simcqt.pro that you cannot get with or prefer to simulationcraft.pro / cmake build? The first one is "kind of" deprecated.

We really need to reduce our build options at some point, far tooo many to maintain... ;)

**Comment by SveSop** [comment]
@scamille Uhm? simulationcraft.pro build now?
```
Graphical User Interface

    Install qt5-qmake. On Ubuntu, the package is called qt5-default.
    Install libqt5webkit5-dev.
    cd your_simc_source_dir
    qmake simcqt.pro
    make
    Optional: Install to ~/SimulationCraft:
        make install
```
From [https://github.com/simulationcraft/simc/wiki/HowToBuild](https://github.com/simulationcraft/simc/wiki/HowToBuild)
So, is that deprecated now?

**Comment by scamille** [comment]
He I guess our documentation is outdated as well.

I just wanted to see if you could give it a try with simulationcraft.pro on your system while you are here. simulationraft.pro is indeed intended as a successor to simcqt.pro. It offers separate builds for cli and the gui (and can thus also replace cd engine && make ). But we do not have any developers using it to regularily build on Linux.

Alternatively, you can also try cmake:
apt install cmake
apt install libqt5webengine (instead of webkit, which is deprecated in newer versions of qt)
cd your_simc_source_dir
mkdir build && cd build
cmake ../
make

I'll try to get around to updating our documentation :-)

**Comment by SveSop** [comment]
doing `qmake simulationcraft.pro && make` seemed to work :)

**Comment by navv1234** [comment]
simcqt.pro is the original "qmake project" of the simulationcraft gui. For various reasons, i wanted to make a somewhat saner version of that, and simulationcraft.pro was born. It is also the only qmake project currently that I personally have any interest in maintaining.

If simcqt.pro is now fundamentally broken for some reason, someone either should fix it, or it should be removed probably ..

**Comment by penguinlust** [comment]
Build is broken on Mac OS 10.12.6 with the removal of simcqt.pro (haven't tried on 10.13.6 nor 10.14.X)

ran "qmake simulationcraft.pro" && "make" and it failed due to the minimum os getting set to 10.8 instead of 10.7

Looks like simulationcraft.pro needs "include (simulationcraft.pri)"

**Comment by scamille** [comment]
Sorry for the inconvenience. We could always restore simcqt.pro if we cannot fix this, but as said since it is really maintained we would like to focus on the simulationcraft.pro instead.

In the simulationcraft.pri file I see QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.7 so I would have guessed this is working fine? the simulationcraft.pri file gets included in all 3 subprojects cli/gui/lib.

There is https://forum.qt.io/topic/76282/qmake_macosx_deployment_target-ignored-on-qt-5-8 / https://bugreports.qt.io/browse/QTBUG-56965?jql=text%20~%20%22QMAKE_MACOSX_DEPLOYMENT_TARGET%22 indicating this might not be working if you are using Qt5.8. Not sure if that is relevant here.

I personally know nothing about osX so navv you need to decide what the best course of action is here. As said, I can restore the simcqt.pro if there are important osX related reasons to keep it, but that brings it back into your maintenance area as well ;)

**Comment by navv1234** [comment]
Sounds like a qt issue yes, the minimum required version is 10.7 and probably will stay that way for the foreseeable future. Could try the workaround in those threads, or update to 5.9 series (which is what our macos nightly releases are built with).

**Comment by scamille** [comment]
```
as a workaround, they can put the variables into <top-level>/.qmake.conf, provided they are fixed and identical throughout the project tree.
```
I am not 100% understanding this. Does this mean putting it in our case simulationcraft.pro instead of the subprojects cli/gui/lib would do the trick?

If so you could try that as well, just c&p the following line somewhere into simulationcraft.pro
```
QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.7
```

**Comment by navv1234** [comment]
At a guess .qmake.conf in the same directory as simulationcraft.pro
