### ISSUE TITLE
Feral Druid

### ISSUE THREAD

**Issue by akis-t** [simulationcraft/simc#4643]
### Describe the bug

Consider this simple script for Feral Druid:
actions=auto_attack
actions+=/tigers_fury
actions+=/rake
actions+=/shred

It will do what it says, it will call rake and shred continuously.

Now comment out the tigers_fury, like this:
actions=auto_attack
#actions+=/tigers_fury
actions+=/rake
actions+=/shred

and run the same script again, it will not call rake or shred anymore!!!

### Additional information
* SimulationCraft Version (required) 810-01
simc-810-01-win64-f78b4aa74e.7z

**Comment by Anatta336** [comment]
I suspect this isn't a bug. 
Rake and shred can only be used if the player is in cat form. Using tiger's fury forces the player into cat form (this is the behaviour in-game and in the simulation.) You'll need to add a line somewhere to get the player into cat form.
```
actions=auto_attack
actions+=/cat_form,if=!buff.cat_form.up
actions+=/rake
actions+=/shred
```
As a side note, because this is a priority list not a step-by-step instruction list it'll cast rake as often as it has energy to do it. You might want to change that line to `actions+=/rake,if=refreshable` so it only uses rake when it's time to refresh the DoT.

**Comment by Xanzara** [comment]
What @Anatta336 writes is correct, and this is the expected behaviour.

**Comment by akis-t** [comment]
OK, thank you, my bad, did not notice the cat form and thought it was weird what it was doing. Thanks.

**Comment by akis-t** [comment]
"You might want to change that line to actions+=/rake,if=refreshable"

Is there a guide to all the available statements / variables in a script?
