### ISSUE TITLE
Program totally useless, again as a reported months ago same issue of unable to download from armory, it goes on and on with no fix

### ISSUE THREAD

**Issue by moonbatmike** [simulationcraft/simc#4793]
### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.

### Additional information
* SimulationCraft Version (required)

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by vituscze** [comment]
Thank you for providing no information whatsoever that could be used to diagnose this problem and fix it.

**Comment by xinye83** [comment]
Seeing same issues here. 
Steps to reproduce:
1. Download latest simc windows nightly build 'simc-815-02-win64-ee448b85c7.7z', and extract it.
2. Open simc GUI
3. click 'Import' tab, choose realm 'Illidan', Character: 'clearhate'
4. Click 'import' button

Expected behavior:
Character details imported into 'simulate' tab

Actual behavior:
Simulate tab shows an error message:
# Profile will be downloaded into a new tab.
#
# Clicking Simulate will create a simc_gui.simc profile for review.

# Unable to generate profile from: 

# Unable to download JSON from 'https://us.api.blizzard.com/wow/character/illidan/clearhate?fields=talents,items,professions&locale=en_US'.


Same error applies for simc command line tool built from head.

**Comment by xinye83** [comment]
Same issue with simc downloaded two months ago, probably blizzard has changed their API, again.

**Comment by seriallos** [comment]
Armory API has basically been broken all day today - this is on Blizzard's side.

If you build SimC yourself, you have to provide your own API credentials: https://github.com/simulationcraft/simc/wiki/BattleArmoryAPI

**Comment by xinye83** [comment]
yeah i've been using command line tools with my own API credentials for years.

This is most likely a blizzard issue then.

**Comment by vituscze** [comment]
Armory API should be alright now. If the issue persists, please open a new issue.
