### ISSUE TITLE
Survival Hunter Profile Corrections

### ISSUE THREAD

**Issue by Crelam** [simulationcraft/simc#4939]
Recently the recommended food in T24_Hunter_Survival.simc was changed to mechdowels_big_mech, however when double checking that recommendation it shows that is not the case and it should be baked_port_tato.

Here is a link to my testing: https://www.raidbots.com/simbot/report/vfsEfCUQkNXu1dYz9CJSQ2

Also, line 134 seems to do nothing.

"actions.st+=/mongoose_bite,if=buff.mongoose_fury.stack>5&!cooldown.coordinated_assault.remains"

Mongoose Fury Stacks can never be greater than five, as it caps at five.

**Comment by scamille** [comment]
@Thyminde

**Comment by Thyminde** [comment]
"actions.st+=/mongoose_bite,if=buff.mongoose_fury.stack>5&!cooldown.coordinated_assault.remains"
This indeed wouldnt work for the reasons you explained, I have removed the line as it was very slight loss of dps even after fixing it.

I have honestly no idea how it got there other than perhaps suddenly having legion flashbacks when I split the actionlist around EP release, since it stacked to 6 back in legion. ^^ But at least it hasn't been doing any harm.

The food issue arised when all hunter specs shared the same food consumable and transitions were being made from agi to secondary stat foods,  Jayeasy has put in a commit to split food usage again.
