### ISSUE TITLE
SimC encountered error - Unable to download item id '132737'

### ISSUE THREAD

**Issue by DruidDobby** [simulationcraft/simc#5026]
### Describe the bug
When attempting to generate stats for my character, issue occurred saying it was "unable to download item id '132737' at slot shoulders"

### Expected behavior
Item cannot be found?

### To Reproduce
Using the 'Cavern Slitherer Pauldrons' in shoulder slot on character. Dropped off of Lady Anacondra in the Wailing Caverns. Using these shoulders while using SimCraft seemed to be the issue

### Additional information
SimulationCraft 8.3.0 - Release 1

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/
Pastebin link:
https://pastebin.com/RBLYuwcs

**Comment by DruidDobby** [comment]
Sorry if this isn't submitted with all information required etc. Let me know if anything is wrong/if anything needs to be added

**Comment by scamille** [comment]
Please try again with the latest nightly from http://downloads.simulationcraft.org/?C=M;O=D 

There seem to be always intermittent problems for low level item downloads, which are out of our control. High level items and nowadays timewalking items are included in SimC, so you should not have any problems there.

Closing this, since I assume your profile is outdated anyway.
