### ISSUE TITLE
Arms Warrior "hac" list underperforms on T25 profile

### ISSUE THREAD

**Issue by Hekili** [simulationcraft/simc#5040]
### Describe the bug
The "hac" list appears intended to sync some abilities around add waves.  However, this list results in lower DPS than if it were simply deleted.

### Expected behavior
Arms Warrior DPS should sim higher *in Hectic Add Cleave* with a special HAC list than without it.

### To Reproduce
I ran the linked sim comparison (T25 Arms Warrior vs DisableHAC).

![image](https://user-images.githubusercontent.com/9438134/73813183-3443e300-47ad-11ea-9e29-245840308763.png)

![image](https://user-images.githubusercontent.com/9438134/73813193-3c9c1e00-47ad-11ea-86dd-1812f32c69d4.png)

https://www.raidbots.com/simbot/report/7RhNTanVwZtYojxSJ8LGja/simc

The only change is deleting the `run_action_list` entry for `hac`.

### Additional information
* SimulationCraft Version (required)
Nightly (830-02) e3675eb6d6

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files
N/A

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/
N/A

**Comment by Hekili** [comment]
Additional info:

I ran a comparison for T24 as well, since Corruption in the T25 profile is a bit out of hand (740???).

![image](https://user-images.githubusercontent.com/9438134/73813355-bb915680-47ad-11ea-9eb5-2a4b1b6d8c37.png)

![image](https://user-images.githubusercontent.com/9438134/73813371-c64beb80-47ad-11ea-8a4e-82fcc8fe2d59.png)

https://www.raidbots.com/simbot/report/vbKDYUeJp55wf2j36j9GFf/simc

Essentially, the same result.

**Comment by Archimtiros** [comment]
HAC hasn't really been touched since the start of the expansion, and there have been a few changes since then, so it could stand to be improved. A lot of the difference you're seeing relates to Lucid Dreams interactions with Test of Might and how utterly insane its scaling has spiraled out of control (which is largely wasted on short lived adds, and why your comparison shows such a pronounced increase in priority damage). Strictly speaking, if you were to optimize a HAC style encounter, you either wouldn't be using Test of Might anyway, which would push back in favor of using CDs on waves of adds instead of the boss (or would just spec Cleave).

As for Corruption, a bonus id was initially added to give the profile an extra 800 corruption in order to make Heart of Darkness work as during early development corruption bonuses didn't actually add the stat. After that was fixed, the bonus was left in so that Heart of Darkness could continue to work when Corruption bonuses were removed (for purposes of Hero Damage/Bloodmallet charts). It is completely cosmetic and has no actual impact on the simulation - the actual amount of corruption bonuses being used is within band (95 = 35 after resists).

**Comment by Hekili** [comment]
I understand.  Is there a talent build for an actual HAC encounter where this list would be more optimal?  Or should it be disabled pending revisions where it would assist?

Left as-is, it may provide deceptive results for HecticAddCleave sims.

**Comment by scamille** [comment]
@Archimtiros is there anything from this still relevant for shadowlands, or can this be closed? I assume that it is unlikely that bfa APL will get improved at this point in time.
