### ISSUE TITLE
Balance Druid: solar_wrath.ap_check

### ISSUE THREAD

**Issue by akis-t** [simulationcraft/simc#5057]
Hey guys, is there a wiki/help file that describes what "solar_wrath.ap_check" is meant to do, and similarly some explanation for other cryptic variables/functions used in scripts? It would be very helpful for people trying to understand or tweak scripts. Many thanks

**Comment by Melekus** [comment]
There are wiki pages for every class, such as https://github.com/simulationcraft/simc/wiki/Druids
That said, updating the wiki is voluntary work and some features such as ap_check may be missing from it.

If you're familiar with C++ you can check the create_expression() functions in the class module to check the code itself. ap_check seems to be defined in two places: https://github.com/simulationcraft/simc/blob/bfa-dev/engine/class_modules/sc_druid.cpp#L2371 and https://github.com/simulationcraft/simc/blob/bfa-dev/engine/class_modules/sc_druid.cpp#L9915
They seem to do essentially the same thing, one checks the action where the conditional statement takes place (such as ``actions+=full_moon,if=ap_check`` ) and the other is a substatement of an action (for example ``if=solar_wrath.ap_check``)

It seems to be comparing (1) your current amount of astral power + the amount gained from casting the ability + other modifiers (streaking stars and nature's balance, not sure what those do) to (2) your base amount of Astral Power + whatever is specified after ap_check (for example ap_check.20 would compare it against base resources + 20). It returns 1 if the first value is higher, and 0 otherwise.

**Comment by Jundarer** [comment]
It's a helper expression that allows the apl writer to easily make sure the action doesn't overcap. Without a spell in front it checks the action and otherwise the specified spell (solar_wrath.ap_check checks if solar wrath would overcap for example). The check is simply the current astral power+astral power generated by the action+passive nature's balance astral power generated during the execute time+a possible shooting stars proc. Both talent parts are of course only if the respective talent is active.

**Comment by Jundarer** [comment]
Closing as this isn't a bug but rather a question that should be asked in the discord. Added a description to the wiki though
