### ISSUE TITLE
Outlaw Rogue - Changing Simc Defaults APL with Weaponmaster talent

### ISSUE THREAD

**Issue by Mysthen** [simulationcraft/simc#5061]
Hello,

I'd like to report a request for Outlaw Rogue playing with Weaponmaster talent instead of the commonly used Quick Draw.

With this talent set, we never use the spell Pistol Shot even while having an Opportunity proc. But the Simc Defaults APL uses Pistol Shot with Opportunity procs, resulting in a simulated DPS loss.

Also, while playing with 3x Keep your wits about you azerite traits, according to my in game tests, the roll of dice Skull and Crossbones brings a lot DPS but the Simc Defaults APL re-roll the dices while having it.

So is it possible to modify the Outlaw Rogue Simc Defaults APL in this way ?

Thank you very much for your support,
Best regards,
Mysthenia

**Comment by Mystler** [comment]
Do you have anything to back this up? Even with 3 Keep and no Pistol Shot affecting azerite powers, I see no gain at all in not using Pistol Shot with Weaponmaster.

About the other point, while 3xKeep is something people try not to play anyway, I also see at best a neutral sim for keeping Skull and Crossbones on a single target. Due to how Keep works, I think it is obvious that with multiple targets during blade flurry Skull and Crossbones is getting pretty much worthless too.
