### ISSUE TITLE
Simcraft Öffnet nicht mit  /simc

### ISSUE THREAD

**Issue by managerx1982** [simulationcraft/simc#5080]
Hallo Leute 

 Habe seid Paar tagen neuen Rechner ( gamming ) mir ist auf gefallen das ich das addon Simulationcraft nicht öffnen kann über /simc könnt ihr mir da ein Rat geben wo ran das liegen kann oder das Problem bekannt ist 

Danke

**Comment by scamille** [comment]
Hi,

This should go to https://github.com/simulationcraft/simc-addon since it has nothing to do with SimulationCraft itself. We can unfortunately give you support only in English as well.

That said, I think there are currently no known problems with the simc addon not opening. It is likely a problem on your end. Make sure the addon is loaded correctly, it should also be visible as a minimap icon.
