### ISSUE TITLE
Wrong stats appears

### ISSUE THREAD

**Issue by alexd369** [simulationcraft/simc#5173]
Hi
When I import my character, my Haste has not the good value, 31% in SimC instead of 54% in wow armory.
 Is it a Expedient corruption problem with SimC ?

### Additional information
SimulationCraft Version 830-01

**Comment by scamille** [comment]
Please try a nightly release from https://www.simulationcraft.org/download.html

This was fixed a few weeks ago, and the correct stat value should now be shown in SimulationCraft.

Before that fix the haste value was still correct when doing the simulation, it just was not shown correctly in the gear section.

**Comment by alexd369** [comment]
I tried with simc-830-02-win64-396ccdc5d9 and still the same issue, 31.32% haste ( unbuffed ) instead of 54%
but if you tell me this is just a display issue in the stats section it's ok !
thanks for the help.

**Comment by scamille** [comment]
You are correct in that it is not included in the unbuffed section. I think the fix was that it now is at least included in the raid-buffed section :-)

But yeah in any case it does work correctly, it is just the way we implemented this through buffs that it still does not properly show in the unbuffed section.
