### ISSUE TITLE
Crash immediately after press "simulate"

### ISSUE THREAD

**Issue by MainX342** [simulationcraft/simc#5404]
In the latest versions (simc-901-01-win64-d3fbc38 and simc-901-01-win64-0947610) I can't simulate any input with covenant=X (0-5 or kyrian, venthyr... it doesn't matter). Immediately crash after press "simulate". But it's work fine without covenant string. Also, in version (simc-901-01-win64-ef9d1e3) i can simulate same text with covenant=X.
Win10 Pro 64bit
![Left_-_new,_Righ_-_old](https://user-images.githubusercontent.com/64480594/95677778-88228980-0bd0-11eb-8e4f-08a949ab5f0f.gif)

**Comment by scamille** [comment]
As mentioned in discord, please post your input here, so we can replicate.

Since this crashes when you hit simulate, it should not have anything to do with the GUI itself and is just related to a rogue/covenant problem.

**Comment by scamille** [comment]
cc @simulationcraft/rogue

**Comment by MainX342** [comment]
It's not rogue/covenant problem, coz i fixed it with clean reinstall windows. I don't know why the problem only appeared with the **last two** versions of simulationcraft, but now all works fine

**Comment by scamille** [comment]
Hmm did you overclock your computer or something other that could explain a unstable condition under high cpu load? But that usually results in a freeze or complete system crash, rather than only the process closing.

Since you stated that this was only happening with a covenant= line that usually means a problem in the simc engine, and not something OS related. Strange that a windows reinstall resolved the problem for you, but at least it is working now :-)

**Comment by MainX342** [comment]
No OC, no high cpu usage, nothing unusual, as you can see in gif, I ran 2 identical sim in different versions, newest - crash, older - nope. Idk too why reinstall helped, but the fact is that the problem occurred only with the string **covenant=X**. I think we can close the issue if the problem is solved.
