### ISSUE TITLE
GUI missing includes

### ISSUE THREAD

**Issue by SveSop** [simulationcraft/simc#5430]
### Describe the bug
Using Ubuntu 18.04, and QT5 5.9.5, build seems to fail with:
```
In file included from ../qt/sc_importWindow.cpp:3:
../qt/MainWindow.hpp:64:8: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
   64 |   std::shared_ptr<sim_t> sim;
      |        ^~~~~~~~~~
../qt/MainWindow.hpp:1:1: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
  +++ |+#include <memory>
    1 | // ==========================================================================
../qt/MainWindow.hpp:65:8: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
   65 |   std::shared_ptr<sim_t> import_sim;
      |        ^~~~~~~~~~

```
And loads more lines

### Additional information
I assume this is due to Ubuntu 18.04 having too old QT5, but before i start messing with custom QT5 versions, id like to know what version is required? Ubuntu Focal got 5.12.8, so if that would suffice, i would rather backport that myself than to mess around with the webinstaller from qt.io (as it will not install "system-wide", but needs all kinds of overrides and whatnot)

**Comment by scamille** [comment]
This has nothing to do with QT, it just means we are missing to include some headers.
This can often occur on some build systems but not on others, which have the required header included transitively through some other standard library header (but which should not be relied on, but that is what is happening here).

I'll take a look and fix it. It might be a bit trial and error because I cannot replicate it at least on my system (WSL2 for Windows, Ubuntu 20.04)

**Comment by scamille** [comment]
Please try again with e7a3053b8155733be553df0421b480cb4d0c2cf4
If there are still error, please post them here as well.

**Comment by SveSop** [comment]
> Please try again with [e7a3053](https://github.com/simulationcraft/simc/commit/e7a3053b8155733be553df0421b480cb4d0c2cf4)
> If there are still error, please post them here as well.

Compiles fine now! Thanks :) Closing issue - Swift fix :+1:
