### ISSUE TITLE
[Shaman] Primordial Wave is cast right after Flame Shock

### ISSUE THREAD

**Issue by raethkcj** [simulationcraft/simc#5616]
### Describe the bug
Primordial Wave is cast right after Flame Shock at the start of a single target fight for Elemental Shamans with Necrolord Covenant.

### Expected behavior
Unless I'm misunderstanding a mechanic, I think PW should be cast instead of Flame Shock; Flame Shock shouldn't be hard-cast until ~18 seconds in.

### Additional information
* SimulationCraft Version (required)
Weekly (902-01)
https://www.raidbots.com/simbot/report/mm4PDXmBvp9FZP89J84ny9

**Comment by wfarr** [comment]
Hey @raethkcj --

simc was modeling this incorrectly before, but has been fixed as of c6e01258a5e797423b29cab222aba39679af69ca and now matches the in-game behavior.

Primordial Wave applies Flame Shock on _impact_ in-game, not on cast. Primordial Wave also happens to have a travel time. The end result is that this prevents you from properly pre-casting Lava Burst -> Primordial Wave and getting the guaranteed critical strike, because Flame Shock won't be applied to the target until after the Lava Burst has made impact.

Thanks for the report!

**Comment by raethkcj** [comment]
Thanks for the insight, that makes sense in the case if your precast is Lava Burst. But in my case I have Elemental Blast talented, and the sim (and me) are both casting that first, which means that Flame Shock cast can be skipped.

**Comment by wfarr** [comment]
I took a look at making this change, but in my testing I found it to come out slightly worse overall.

https://www.raidbots.com/simbot/report/vAbWTrSX3YuFYdGZpWzy7L

https://www.raidbots.com/simbot/report/gRF6K6gDuNkTin5VgMimkf

If you have a specific APL change that you can demonstrate results in a gain, I'm happy to update it, but my initial investigations show this to be break-even or a small loss.

**Comment by raethkcj** [comment]
I'm not experienced with APL, but surely this deserves a closer look. You're spending an entire extra GCD for *just* the initial damage of Flame Shock, which is close to the lowest damage per cast time you can get.

**Comment by raethkcj** [comment]
?

**Comment by raethkcj** [comment]
?
