### ISSUE TITLE
[not an issue] Fedora builds

### ISSUE THREAD

**Issue by elegos** [simulationcraft/simc#5675]
Hello!

I'm setting up an automatic snapshot builds of simulationcraft (cli and gui).

At the moment I've prepared the cli-only version, which is available here: https://copr.fedorainfracloud.org/coprs/elegos/simulationcraft/
Source code: https://github.com/elegos/fedora-simulationcraft

Next I'm planning to add the `simulationcraft-gui` package in the same copr repository and a CI integration to run the build daily.

P.S.
I've added the profiles in `/usr/share/simulationcraft-cli/profiles` - but I'm no simc expert. Is it ok to store them there?

**Comment by scamille** [comment]
Thanks for the information. We had linux packages in the past and resolved path problems with it, but if you still encounter something or need to adjust it, let us know.

I can't say anything about the profiles path since I am no linux expert - whatever is a appropriate readonly shared path.

Is there a reason you require qt-devel for the cli? That should in theory be unnecessary with  -DBUILD_GUI=OFF, since the cli does not rely on qt at all.

**Comment by elegos** [comment]
It is necessary because otherwise it won't find cmake vars (for some reason).

BTW yes, there is a small issue about the GUI: how can I tell the compiler to point at to search for Welcome.html (and relative Welcome.png)?

**Comment by scamille** [comment]
https://github.com/simulationcraft/simc/blob/shadowlands/qt/sc_WelcomeTab.cpp
uses SC_PATHS::getDataPaths() which is defined at https://github.com/simulationcraft/simc/blob/shadowlands/qt/sc_window.cpp#L58

I think you want to have SC_TO_INSTALL defined so that it adds QStandardPaths::standardLocations( QStandardPaths::DataLocation ) which according to https://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum is ```"~/.local/share/<APPNAME>", "/usr/local/share/<APPNAME>", "/usr/share/<APPNAME>"```

I think ```<APPNAME>``` is "SimulationCraft" as defined in https://github.com/simulationcraft/simc/blob/shadowlands/qt/main.cpp#L78

**Comment by elegos** [comment]
I beg you pardon, but how can I define SC_TO_INSTALL? Via a patch or an extra flag?

**Comment by scamille** [comment]
Right. Hmm I don't think our cmake script has this implemented right now. It needs something like we have in the qt one here: https://github.com/simulationcraft/simc/blob/shadowlands/gui/gui.pro#L21

Are you good with cmake and know by chance how this can be accomplished? Googling gives https://cmake.org/cmake/help/latest/command/add_compile_definitions.html#command:add_compile_definitions which I would connect to a option like we have at https://github.com/simulationcraft/simc/blob/shadowlands/CMakeLists.txt#L12

**Comment by elegos** [comment]
Hmmm I'm a software engineer, I'm going to look into it :D

BTW what about the icon? Running the SIMC app shows the default X11 icon, which is pretty ugly :P

**Comment by scamille** [comment]
Well the whole GUI is ugly, just use Raidbots :P 

To build the GUI, it might honestly be better to use qmake instead of cmake, since that is also what is used for windows and macos nightly builds. See https://github.com/simulationcraft/simc/wiki/HowToBuild#graphical-user-interface-using-qmake or https://github.com/simulationcraft/simc-publish/blob/master/.github/workflows/nightly.yml#L64

**Comment by elegos** [comment]
I think I made it. By default the shared path should be `/usr/share/ORG/APP`, which in this case is `/usr/share/SimulationCraft/SimulationCraft`.

Now I need to add a `SimulationCraft.desktop` file defining the app's icon. If I'm not wrong, that should be sufficient to overwrite the app's default.

Is there any icon I can use?

**Comment by scamille** [comment]
https://github.com/simulationcraft/simc/blob/shadowlands/simcqt.rc uses https://github.com/simulationcraft/simc/blob/shadowlands/qt/icon/Simcraft2.ico

It looks quite ugly, but I am not sure if we have a higher resolution version of it.

**Comment by scamille** [comment]
So https://github.com/simulationcraft/simc/blob/shadowlands/qt/icon/SimulationCraft.xpm seems to have a better resolution, even though it is in some strange old format I never heard until today. But Gimp opens it :-)

**Comment by elegos** [comment]
Tah-daa!

Now the repository is complete. The only thing that I'm missing is some sort of cron to automatically run it daily (or... nightly? :stuck_out_tongue_closed_eyes: )

I tried with drone.io, but the cloud version disables cron jobs. I'm going to see if I can achieve it with Travis.

**Comment by scamille** [comment]
We use github actions for the windows and macos nightly builds. Have a look at https://github.com/simulationcraft/simc-publish and feel free to just copy-paste whatever you like from this to your own CI setup.

**Comment by elegos** [comment]
Resolved via a couple of lines of travis-ci :smile: 

BTW if you're interested, here is an interesting patch you might want to integrate in the cmake's build file:

https://github.com/elegos/fedora-simulationcraft/blob/main/simulationcraft-gui/gui-sc-to-install.patch

**Comment by scamille** [comment]
Thanks, added in 7718419bf76e5e591b68500086db6db3bec8f3c8

Next time, feel free to just open a pull request if you like.

**Comment by seanpeters86** [comment]
Closing for now, feel free to reopen if an issue comes up. Always welcome to start a discussion in the discord as well. https://discord.gg/tFR2uvK

**Comment by scamille** [comment]
I added a line to https://www.simulationcraft.org/download.html mentioning your fedora copr package. This should help inform people who are interested in using your automated simc build as a alternative to building it manually.
