### ISSUE TITLE
Spirit Shell can't be cast by Discipline priests

### ISSUE THREAD

**Issue by nakda** [simulationcraft/simc#5681]
### Describe the bug
> unable to create action: spirit_shell

This error is raised when trying to run a simulation after importing my Discipline Priest, and casting [Spirit Shell](https://www.wowhead.com/spell=109964/spirit-shell).

### Expected behavior
Simulation should run properly as the simulation target character got the talent enabled.

### To Reproduce
1. Import Sample Profile: Pre-raid Discipline Priest
2. Edit talent configuration to enable Spirit Shell (e.g.: 3323112)
3. Add the line `actions+=/spirit_shell` after `actions+=/power_infusion` (or whatever valid line)
4. Run the simulation

### Additional information
* SimulationCraft Version: 902-01

* **simc_gui.simc** file or contents
[simc_gui.zip](https://github.com/simulationcraft/simc/files/5719500/simc_gui.zip)

**Comment by scamille** [comment]
Discipline priests have only purely DPS related affect implemented, no healing or absorb. This is thus to be expected, see #2775

For DPS related things, have a look at #5640 for some remaining problems even there.

Unless someone picks up development for discipline priests and wants to fully model healing, that will not change any time soon. We always accept pull requests though.

**Comment by nakda** [comment]
> Discipline priests have only purely DPS related affect implemented, no healing or absorb. This is thus to be expected, see #2775
> 
> For DPS related things, have a look at #5640 for some remaining problems even there.
> 
> Unless someone picks up development for discipline priests and wants to fully model healing, that will not change any time soon. We always accept pull requests though.

Thank you for the input!

As Power Word: Shield is working I guessed that all spells were implemented but only simulated towards DPS scenarios. If I understand correctly, all DPS abilities are implemented and some others might but it's not to be expected. Right?

I was using Spirit Shell in my simulation because I want to evaluate my DPS during the Spirit Shell ramp: is it better to use my CDs whenever they are up or should I only use X/Y ability when Spirit Shell is applied. Unfortunately, I couldn't find any other similar ability to circumvent the lack of implementation (instant cast, no GCD, 1min CD). Is there a custom action I can implement to fake this behavior or something?

Edit: regarding PR, I'm terrible at C++ dev. I'll look at the contribution guide and maybe look for a way to help.

**Comment by scamille** [comment]
Yes at some point in the past, most healing spells had been implemented for discipline priest. Atonment has been actively removed because of the maintenance burden, and anything newer than I think legion has never been implemented. But simple things like PW:S have not been actively removed. That explains why some things are still available, and others aren't.

It is definitely possible to simulate a healer with SimulationCraft to eg. get stat weights for some simple scenarios like full dps, single target healing, group healing. What you would do with such results and how you combine them to gain insights is of course up to you.

I still don't really understand what you are trying to simulate: Do you want to compare dps inside the spirit shell timeframe and outside? that is not something which would be easy to answer, even with some fake action.

**Comment by nakda** [comment]
Sorry if my previous statement was not clear.

What I'm trying to achieve is optimizing my dps and healing burst as a Discipline priest. For example, I would like to compare dps simulation when casting Mindgames whenever it's up versus keeping it for when Spirit Shell is up.

I wanted to do something like this:
```
actions+=/spirit_shell
actions+=/mindgames,if=buff.spirit_shell.up
```

vs 

```
actions+=/spirit_shell
actions+=/mindgames
```

**Comment by scamille** [comment]
Ah ok I understand. Well it should be quite simple to add a Spirit Shell action with a associated buff, without it doing much.
