### ISSUE TITLE
Adding trinkets and removing default trinkets from action list don't seem to work

### ISSUE THREAD

**Issue by misosoup7** [simulationcraft/simc#5748]
So I added the following line and it doesn't seem to do anything:
`actions.dmg_trinkets+=/use_item,name=tablet_of_despair`

I've also tried commenting out a line in the default action list
`# actions.dmg_trinkets+=/use_item,name=dreadfire_vessel`
 But neither seem to make any changes to simulation results when you look at the action priority list. It still shows dreadfire vessel as an option but not tablet of despair.

Is there something I'm doing wrong or simc is just basically ignoring my customized action priority list?

I'm also using the GUI version and not the console version on Win64

Edit: formatting and additional information.

**Comment by scamille** [comment]
Are you appending a complete set of actions to the profile you are simulating, or just those single lines you mention?
The latter will not work, as there is no automatic merge between the integrated default APL and single lines appended to the profile for a specific action list (dmg_trinkets).

Please try adding the full action priorty list to the profile you are trying to simulate (you can eg. find it in the html report in the profile section if you simulate your character first), and then making adjustments there.

**Comment by seanpeters86** [comment]
@misosoup7 so this is the shadow APL specifically yes?

The shadow APL is a tiered system for on use trinkets:
1. Call `cds` action list in `main` action list
2. Call `trinkets` action list
3. Call specific trinkets in that action list with unique on use conditions
4. Call action list `dmg_trinkets` to specifically group on use dmg trinkets in a quick list that all share the same condition: `if=(!talent.hungering_void.enabled|debuff.hungering_void.up)&(buff.voidform.up|cooldown.void_eruption.remains>10)`
5. Default fall back for any trinkets NOT specified: `actions.trinkets+=/use_items,if=buff.voidform.up|buff.power_infusion.up|cooldown.void_eruption.remains>10`. This condition is here so that we do not have to hard code each and every trinket, this condition will be used for all on use trinkets that were not tripped by the above conditions.

The reason your change doesn't seem to do anything is because the trinket condition falls back to the default one. So you are comparing the overwrite action to the default action.

Feel free to ask questions in discord if you have any issues.
