### ISSUE TITLE
Black screen in Home, Help, and Results

### ISSUE THREAD

**Issue by auddie2015** [simulationcraft/simc#6283]
### Describe the bug
Anything that is html results in a completely black window. The results html can be loaded in my web browser normally.

### Expected behavior
I should be able to see the html content inside the client.

### To Reproduce
It is persistent on every run.

### Additional information
915-01 WebEngine (simc-915-01-win64_qt5-540f6fb.7z)
(simc-915-01-win64-e40f895.7z) has the same issue

* **simc_gui.simc** file or contents

[simc_gui.zip](https://github.com/simulationcraft/simc/files/7874129/simc_gui.zip)

**Comment by scamille** [comment]
Thanks for the report. This is most likely a issue with the UI Framework (Qt) that we use for the GUI, which includes showing the embedded web pages.

Can you please try to upgrade your graphic card driver first to see if that helps?

If you use some special display resolution, maybe try adjusting those (eg. setting display scaling to 100% instead of some higher value)

Also try setting the UI language in the SimulationCraft GUI to English (which might help if you use any of the other translated languages).

**Comment by auddie2015** [comment]
It was display settings in my video control panel. I am guessing SuperResolution. I disabled it and now I see everything just fine. 

Thanks!
