### ISSUE TITLE
Reactive Defense Matrix undersims

### ISSUE THREAD

**Issue by Oneirocritica** [simulationcraft/simc#6377]
### Describe the bug
Reactive Defense Matrix undersims considerably.

### Expected behavior
Reactive Defense Matrix is one of the highest DPS trinkets for tanks in the game at the moment. The sim values do not correspond with the observed in-game behavior. The discrepancy is large enough that there is no way to explain it other than a flawed implementation.

### To Reproduce
Sim a tank character with Reactive Defense Matrix equipped. Test it actually in game. Observe difference. 

### Additional information
Using latest SimCraft. 
Example, 
Simc result: https://www.raidbots.com/simbot/report/uHR66UguXPQosnehjZuHaY
In-game 9 minute dummy test: https://cdn.discordapp.com/attachments/584771571462307855/944747074086404126/unknown.png

**Comment by Dorovon** [comment]
This should be fixed in https://github.com/simulationcraft/simc/commit/c34f5f5fa4e97d766846c75946c04282ec841aba.

To get maximum output from the trinket in simc, you will also need to use the new `shadowlands.reactive_defense_matrix_interval` option, which models how often you drop below 20% hp.

For example, `shadowlands.reactive_defense_matrix_interval=5` will attempt to proc the 30-second cooldown aspect of the trinket once every 5 seconds.
