### ISSUE TITLE
[GUI] zh localization not working

### ISSUE THREAD

**Issue by PatShen** [simulationcraft/simc#6505]
### Describe the bug
I change the GUI Localization to `zh` and restart app, it still show the English version. And any other language has same effect.

### Expected behavior
It should display the correct language version.

### To Reproduce
It reproduce 100% on `simc-920-01-macos-e75cb4b`

### Additional information
* SimulationCraft Version (required): `simc-920-01-macos-e75cb4b`
* Other system info: M1 Pro, macOS 12.1

**Comment by scamille** [comment]
Ok so this is reproducible on windows as well, and it only affects the zh translation. All the other ones are working fine.

**Comment by scamille** [comment]
Should be fixed in https://github.com/simulationcraft/simc/commit/02a9b6fe9ad92e1f4991b40b9c0e940fddad29ea

I don't know why language code cn instead of zh is used in the translation file - or which one is the correct one. It was changed at some point, see https://github.com/simulationcraft/simc/commits/shadowlands/locale/sc_cn.ts . I suspect it was changed to fix auto-detection of the language on chinese system, but I am not sure. Maybe @kuletco knows more about this.

In any case, now the option in the GUI matches the translation file name so things work again. It should be available with the next nightly.
