### ISSUE TITLE
SimulationCraft.exe from version for 9.2.0 fail to start on Win7.

### ISSUE THREAD

**Issue by xStiven** [simulationcraft/simc#6535]
Version SimulationCraft.exe for 9.1.5 working fine, but new one from "simc-920-01-win64" fails to launch, error 0xc0000005.

**Comment by scamille** [comment]
The GUI framework that we are using no longer supports Windows 7. See https://doc.qt.io/qt-6/supported-platforms.html
I assume this is because Windows 7 has reached its end of support in 2020, see  https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information

You might still be able to run the command line version of simc (simc.exe).

**Comment by xStiven** [comment]
Np. Just please, note it on download page, so not to cause confusion %). I been running in circles trying to install all possible missing libraries and update packs ;)

**Comment by scamille** [comment]
> Np. Just please, note it on download page, so not to cause confusion %). I been running in circles trying to install all possible missing libraries and update packs ;)

I added a line to the download page :-)
