### ISSUE TITLE
[Outlaw Rogue] add support Prey on the Weak for stunnable mobs

### ISSUE THREAD

**Issue by 3axap4eHko** [simulationcraft/simc#6669]
### Is your feature request related to a problem? Please describe.
The 40th level talent tier for Rogue provides CC-oriented talents and one of them is Prey on the Weak. Would be great to have a damage simulation for stunnable mobs. The motivation is that only this talent increases damage in the 40th level tier.

### Describe the solution you'd like
Add Kidney Shot to finishers to get +10% damage Prey on the Weak buff for 6 seconds

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by Horaddrim** [comment]
From what I could find in https://github.com/simulationcraft/simc/blob/cf9e6e6c02b2afa67a8965aba5c05f5c007c6d2d/engine/sim/sim.hpp#L100 

the default target for sims is modelled as a player, and in the Rogue model, there is a reference to applying the debuff on targets:

https://github.com/simulationcraft/simc/blob/cf9e6e6c02b2afa67a8965aba5c05f5c007c6d2d/engine/class_modules/sc_rogue.cpp#L6506-L6513

which means that there is technically nothing to change in the engine itself for it to work and is just a matter of modifying your APL to use KS before any finisher to sim your damage Prey on the Weak.

You can use something like this in your action list:
`actions+=/kidney_shot,if=(buff.adrenaline_rush.up&combo_points=1)` to just use KS while you have AR. I've wrote it to use with 1 CP since you can get the buff regardless, and it last 6 secs, so you can go deeper into min-maxing KS with this [doc](https://github.com/simulationcraft/simc/wiki/Rogues) if you're feeling down for it.

**with that said, I'm not entirely sure on the state of CC's as a whole in the engine, would be cool if someone could double check what I've found**

**Comment by 3axap4eHko** [comment]
Seems like the following might help
```
actions.finish+=/kidney_shot,if=(buff.symbols_of_death.up&combo_points=5)
```
How to be with a diminishing return mechanism for stuns in SimCraft?

**Comment by EvanMichaels** [comment]
Using stuns in the APL with Prey should be supported. Although last I looked this was not a DPS increase.

Sub has this line as a reference:
actions.stealthed+=/cheap_shot,if=!target.is_boss&combo_points.deficit>=1&buff.shot_in_the_dark.up&energy.time_to_40>gcd.max
