### ISSUE TITLE
Add the ability to use a trinket pre-combat

### ISSUE THREAD

**Issue by Notter** [simulationcraft/simc#7199]
### **Issue**:
Some trinkets (such as [Algeth'ar Puzzle Box](https://www.wowhead.com/item=193701/algethar-puzzle-box)) have a channeled ability which gives the character a self-buff.
Currently trinkets are used by a general-trinket APL command after certain abilities (E.g.: For Assassination, they are used after "Deathmark").
These trinkets in-game can be used pre-pull to start combat with their buff, but SimC APL doesn't feature such an option. 

### **Request**:
We would like the APL to feature an option to use a trinket pre-combat.
Afterwards, it should return to the general-trinket use rotation.

### **Example**:
Assassination Rogue could potentially have this opener:

**pre-combat**
1. Use trinket
2. Stealth

**combat-start**

3. Shadowstep to target
4. execute opener

**Comment by Hurstilol** [comment]
This already exists as a possible thing for the APL.
![image](https://user-images.githubusercontent.com/85832226/209655734-4af85df6-ebf8-46db-a0db-1328c610cb19.png)
Here for example a quick and dirty made one for the assarogue profile.
https://www.raidbots.com/simbot/report/huyPmSmLKJkFhFMFiYQf2x/simc

The only thing you have to add is a line that looks like this:

actions.precombat+=/use_item,name=algethar_puzzle_box

and it will automatically do what you requested. But as you can see in the examplesim, the precombattrinket is a loss compared to the normal usage of this profile. Have fun adjusting it (esp since im not a rogue TC so my quick and dirty solution might not be the optimal usage for rogues) 

And as a small sidenote: Trinketusage heavily depends on the spec you are looking into. While Rogue has a general TrinketAPL the WW APL has exceptions and a way different way to include the trinkets into the APL.
