### ISSUE TITLE
Affliction soul rot not showing in Single target sims

### ISSUE THREAD

**Issue by Bobbyteo** [simulationcraft/simc#7262]
### Describe the bug
Soul Rot damge breakdown not shown in sims

### Expected behavior
missing chunk of damage

### To Reproduce
just run any single target sim

### Additional information
World of Warcraft 10.0.2.47213 Live (hotfix 2023-01-11/47213, git build [00b91f4](https://github.com/simulationcraft/simc/commit/00b91f4))

* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/

**Comment by Azevara** [comment]
Given the time at which this issue was reported and the lack of an example case, it is impossible to know if this was a temporary problem with APL changes in the past. Additionally, the action for Soul Rot executes fine in a test sim in the most current build at time of writing.

Please open a new issue and provide an example raidbots link if you continue to encounter this problem.
