### ISSUE TITLE
Variable named nil causing build break on my setup

### ISSUE THREAD

**Issue by Debuggernaut** [simulationcraft/simc#7716]
Hey team, this could be a misconfiguration on my machine, but this commit:

https://github.com/simulationcraft/simc/commit/ac44d83cbb37454a67d8492090a4ca8d524cffd8

is causing me to hit a build break on my Mac.  It says that nil is already defined as nullptr and treats it like a reserved keyword.

> In file included from ../qt/sc_ImportThread.cpp:13:
> ../engine/sim/sim.hpp:231:13: error: expected member name or ';' after declaration specifiers
>     buff_t* nil; // generic global fallback buff
>     ~~~~~~  ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/MacTypes.h:92:19: note: expanded from macro 'nil'
>       #define nil nullptr
>                   ^

I was able to work around it locally for now by reverting ac44d83cbb37454a67d8492090a4ca8d524cffd8 and 8064d6c4f19bf7785f168bfa289d265f14c4cc86

**Comment by Dorovon** [comment]
This should be fixed in https://github.com/simulationcraft/simc/commit/24b256a29f50686870be41b614c46d72d72d0090. I didn't realize that some platforms used nil as an alias for nullptr or NULL.

**Comment by scamille** [comment]
You can also see the error here: https://github.com/simulationcraft/simc-publish/actions/runs/4921293433/jobs/8790983186#step:6:766

Since we don't build the UI with the normal simc repository CI pipeline, we don't catch it immediately. Might be worth thinking about building the GUI there as well - but it has the potential to slow down things a bit.
