### ISSUE TITLE
Brewmaster should use Touch of Death

### ISSUE THREAD

**Issue by ptarjan** [simulationcraft/simc#8356]
### Is your feature request related to a problem? Please describe.
The HeroRotation addon pointed me here to add touch of death

### Describe the solution you'd like
ToD is one of the highest DPS spells.

**Comment by renanthera** [comment]
This is a known issue, but in the past I was having some trouble with ToD usage being inconsistent, so it was removed from the APL. I'd like to re-add it in the future, but it is not a very high priority, as it won't have a significant impact on results due to how the effect scales.

It would be recommended to use ToD whenever you can execute a target with it, but in game, encounter design may impact your usage substantially.

**Comment by ptarjan** [comment]
Thanks for responding. I guess the main problem for me is that the addon HeroRotation uses your APL to suggest which spell to cast next so if you don't have the spell included it won't suggest it. So if you can do it in any way, even if it doesn't affect your sims that much, that would help out the users of that addon.
