### ISSUE TITLE
Incorrect wait times after channeled abilities

### ISSUE THREAD

**Issue by slappaww** [simulationcraft/simc#8825]
### Describe the bug
Windwalker APL for example after a canceled fist of fury it takes 1.4s or so for the next global to be pressed

### Expected behavior
1s gap for non channeled abilities after a channeled ability

**Comment by renanthera** [comment]
Given that there are 30 different invocations of `fists_of_fury` in the default WW APL alone, it's impossible to tell which one you believe is problematic with this report.

`fists_of_fury_cancel` lasts for exactly 1 (fists of fury) GCD
`fists_of_fury` with `interrupt=1` or `interrupt_if` condition lasts for one (fists of fury) GCD and then cancels on the first tick that occurs after that.
I'm unsure if any of the other channel cancel options are used anywhere, but they may.

The wiki entry for at least a significant fraction of channel options may be found here:
https://github.com/simulationcraft/simc/wiki/ActionLists#channeling

If you believe it is still an issue after this information, please provide more precise steps for replication and/or identify specifically which line you believe is producing incorrect output.

**Comment by slappaww** [comment]
"fists_of_fury_cancel lasts for exactly 1 (fists of fury) GCD"

This is incorrect. It is adding additional ms delay to the GCD. It should be 1s flat but is 1.3

This is true for numerous channeled abilities. Spinning Crane Kick causes an extra 100ms of delay. Grieftorch causes an extra 300ms of delay, etc

None of this behavior is true in game, only in simc

**Comment by renanthera** [comment]
As far as I can ascertain, you are basing your "finding" off of the HTML report sample action list. As a result, this is missing a significant portion of the picture. **In the future, please include more context with your issue, as it makes it much easier to identify if any confusion is occurring.**

If you were to instead inspect debug output, you would realize that the channel is in fact canceled at the appropriate time. Here's a portion of a debug output showing the important details for a Fists of Fury cast invoked by the following APL line:
`fists_of_fury,target_if=max:debuff.keefers_skyreach.remains,if=debuff.skyreach_exhaustion.remains>55&set_bonus.tier29_4pc&active_enemies=1,interrupt=1`
```
3.867 Player 'Katebrew' schedules execute for Action fists_of_fury
3.867 Dot fists_of_fury ticks (0 of 4). duration=2.256 time_to_tick=0.000 remains=2.256
3.867 Player 'Katebrew' schedules execute for Action fists_of_fury_tick
4.431 Dot fists_of_fury ticks (1 of 4). duration=2.256 time_to_tick=0.564 remains=1.692
4.431 Player 'Katebrew' schedules execute for Action fists_of_fury_tick
4.995 Dot fists_of_fury ticks (2 of 4). duration=2.256 time_to_tick=0.564 remains=1.128
4.995 Player 'Katebrew' schedules execute for Action fists_of_fury_tick
4.995 Dot interrupt check: gcd_ready=true action_available=true.
4.995 Dot fists_of_fury fades from Player 'Fluffy_Pillow'
4.995 Player 'Katebrew' fists_of_fury schedule_ready(): cast_finishes=5.096 cast_delay=0.000
```

As of the 8th line of that excerpt, the following method is invoked:
https://github.com/simulationcraft/simc/blob/ef4445f7fc3a87e0ec8d7674bec1283618cf8724/engine/action/dot.cpp#L690-L732

Three important things occur if the interrupt event occurs, much like what went on in the previous example. Note that due to implementation reasons, the action that causes the FoF ticks to occur is implemented as a dot. This is not that important as it's just a convenient way to schedule ticks over some duration that can be canceled.
- `interrupt_immediate_occurred` is set to `false`, as we just interrupted it normally.
- If auto attacks were delayed by the channel, they are appropriately rescheduled.
- The dot is canceled.

This is helpful and points is in the right direction to where we need to go.
Now, if we look where `interrupt_immediate_occurred` gets used, we find this method. This does all of the post-action scheduling to determine when the next foreground action (think "things a player does") is able to be executed.
https://github.com/simulationcraft/simc/blob/ef4445f7fc3a87e0ec8d7674bec1283618cf8724/engine/player/player.cpp#L6264-L6386

It's pretty lengthy, but we only need to focus on the following section:
https://github.com/simulationcraft/simc/blob/ef4445f7fc3a87e0ec8d7674bec1283618cf8724/engine/player/player.cpp#L6308-L6349

If we `interrupt_immediate`'d the channel, we will end out setting `lag` as done in the first if statement in this block of code, as `ability_lag` is configured for both FoF and SCK.
If we do not `interrupt_immediate` the channel, we will end out setting `lag` as shown on line 6326.

You'll also notice that none of these possible `lag` values are constant, but in fact are sampled from a Truncated Gaussian Distribution, as they are of the simc time type, `timespan_t`.

The `lag` value is then used to schedule the event that allows the next player APL action to occur shortly afterwards.

Conveniently, you have the option of configuring all of these values if you would like. Complete implementation details of `world_lag` and `channel_lag` related options can be found primarily in `sim.cpp`, `player.cpp` and `sc_monk.cpp`.

If you believe that these defaults should be changed, you're more than welcome to submit a more detailed issue or PR with suggested values, and data to support it.

**Comment by slappaww** [comment]
Yes, those lag options are drastically different from in game behavior. This affects monk abilities as mentioned as well as things like Grieftorch. I wouldn't be surprised if it extends to other classes/specs as well. 

There is no lag following these abilities, so I'm not sure why it's implemented in simc. I filed an issue instead of a PR as I'm not sure the extent to which it affects different items and spells.

**Comment by Dorovon** [comment]
Channel lag exists in simc to model the lack of spell queueing after channels.

When you are casting a spell or are on the GCD, the game lets you queue you next spell, which will automatically cast immediately after your cast or the GCD finishes. If you try to cast a spell during a channel, it will simply interrupt the channel early resulting in lost ticks from the channel. Because casting spells immediately following a channel with no delay is unrealistic, simc adds a random delay after a channel ends before the next action is scheduled to model a human casting their next spell after the channel ends (the timing will not be exactly the same every time). Past testing has shown that the default setting of an average of 250 milliseconds of delay for channels is quite reasonable for this game, but you can feel free to adjust the options to lower values if you think they are unrealistically high for you.

**Comment by slappaww** [comment]
This just isn't true lol and is the entire point of the issue. 

For something like Spinning Crane Kick -> Spinning Crane Kick there is ~300ms delay in game due to no queue yes. In real play however any non channel can be queued during spinning crane kick and effective "lag" is standard GCD lag. 

And again, for something like a GCD fists of fury cancel, you absolutely can spell queue and I have done so hundreds or thousands of times with casts on global being less than 10ms delay vs the **300** in simc default. That is a drastic difference that simply does not occur in game. 

300ms is also vastly more than a competent player will see with allowing channels to finish and my own logs have delay between 10-30ms, again a drastic difference from 300 and creates significant differences in results. 

Please do not close issues where you simply don't understand what is happening
