### ISSUE TITLE
Profiles only run the default talent build

### ISSUE THREAD

**Issue by zachpipher123** [simulationcraft/simc#8857]
### Describe the bug
When setting up the profile, the simulation will list all the differnet talent builds but they're at 0

### Expected behavior
I expected to see the median dps for each talent build

### To Reproduce
Please include any steps necessary to recreate the problem, or include logs/data to show what is occurring in game if there is an issue with how something is modeled.
i put in my profile, with this 
single_actor_batch=1 talents=BwQAeJVyolP8xRXAFmS4CX44UBAAAAAASAAAAQShWLJJQSSrRAAAASJHQJJSkQrIJKJJlEEaNi0SrECA  profileset.MYthicstarter+=talents=BwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAIloVSSCkk0aHQAAAASJHQJJSkQrQSKJJlEANJSLtSIA

as my talents with everything else being default
### Additional information
* SimulationCraft Version (required)
1027-01
* If SimulationCraft is crashing, please include your **dxdiag** file - Instructions here - 
  https://us.battle.net/support/en/article/Obtaining-System-Files

* **simc_gui.simc** file or contents
  This file is saved in the same folder as SimulationCraft after each simulation. Make sure to run the 
  simulation that is giving you issues, then include the file here by either uploading to github, 
  copy/pasting the contents, or using http://pastebin.com/
![image](https://github.com/simulationcraft/simc/assets/23176809/903d4142-f9ff-4ca3-b1ac-8de9bbdc7fad)

![image](https://github.com/simulationcraft/simc/assets/23176809/989b6cc9-d02d-46d4-a828-ba8b8c0686f6)

**Comment by renanthera** [comment]
I am struggling to replicate this exact result, see the attached sim. The attached sim is a later version than the version this issue is reported for, though.

I have also rerun my test sim locally on the exact same build, and I am also struggling to replicate the behaviour.

https://www.raidbots.com/simbot/report/aYQ9uDAM5S4ACrRki2qufz

Either way, simc is reporting that the talent string `BwQAeJVyolP8xRXAFmS4CX44UBAAAAAASAAAAQShWLJJQSSrRAAAASJHQJJSkQrIJKJJlEEaNi0SrECA` has an invalid tree hash, which suggests there are issues with configuration.

If replacing that talent string with something exported from the game (after clearing any potential old talent trees from addons, etc) or from WoWhead does not fix the issue, please follow up here and attach a full HTML report and/or input file.

**Comment by Yanlex** [comment]
you can fix this if before download file you uncheck `Use profilesets (for Advanced mode or SimC command line)
`![image](https://github.com/simulationcraft/simc/assets/20624737/8dd407ba-da90-45be-85c4-3ddfddef3486)
