### ISSUE TITLE
GUI crashes

### ISSUE THREAD

**Issue by Tronarr** [simulationcraft/simc#9717]
Hello,

just downloaded the newest version of SimC. Everytime ich double click the exe "SimulationCraft" the GUi starts and immediately crashes (circle of doom, need to close the programm).

In the past i have had almost similar problems and had to refresh der Microsoft Visual C++, which fixed the problem. The current version is up to date, so no clue whats wrong.

Thanks in advance

**Comment by edu5ardo** [comment]
I have the same problem, this has been going on for a month and it doesn't seem like anyone is paying attention to the inability to use the simulator.

**Comment by renanthera** [comment]
The GUI is largely unsupported at this time, as very, very few developers use it.

I'd recommend not using the GUI, as it's much more limited than the CLI binary w.r.t capability and support.
If you must use a GUI, use Raidbots instead.

There was a known [issue](https://github.com/simulationcraft/simc/issues/9311) as you noted that was fixed by updating MS Visual C++, but you're clearly having some different problem.
