### ISSUE TITLE
Website is not secure

### ISSUE THREAD

**Issue by Michael-Cooney** [simulationcraft/simc#9784]
The nightly builds website is not using https, and therefore it's really difficult to download.  I have to jump through a ton of hoops everytime I want to download a built.

**Comment by Pewtro** [comment]
Why does that make it difficult to download the binary?

**Comment by Michael-Cooney** [comment]
Howdy!  It could be a Chrome issue.  If the website isn't secure, I have to grant it special permissions, and frankly, they don't really work all the time.  Sometimes it gets granted and I can access the directory, sometimes it doesn't do anything and I have to backup and try again multiple times.  Then when clicking to download the actual file, sometimes it just doesn't download.  When it does, Chrome flags it as suspect, and asks if I want to "keep" it, but often the button is greyed out and I can't actually keep it.  If everything finally goes through, Windows might delete it (or maybe it's still Chrome).  It's a real chore for something that's supposed to be updates frequently.  Besides, it's a bit suspect for a website not to be secure these days, especially when distributing software.

**Comment by Pewtro** [comment]
I don't have this issue on chrome, so it's either an extension or some other setting you have enabled that causes you issues. 
There are no special permissions you need to give to a website that is http in default chrome or windows, so that is something you have enabled somewhere. 
I tried multiple downloads on multiple PCs and not once was "keep" greyed out. nor did the file get deleted after download. 

The only thing you should need to do is press "keep", and that should be enough, and I don't think that counts as "really difficult" or "a bunch of hoops".

**Comment by renanthera** [comment]
Https unfortunately would introduce both complexity and cost for a glorified ftp server.

If you have any experience with solutions that wouldn't increase difficulty of hosting, do let us know.
